CTT_Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

CTT_Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assign_to_Queue__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If selected, Case will be assigned to the relevant Queue. If not selected, Case will remain assigned to user creating the Case.</inlineHelpText>
        <label>Send To Contact Trace Queue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City_Input__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Is_A_Minor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is to indicate if the contact is a minor or not.</description>
        <label>Person Is A Minor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employed_or_Admitted_Location_Type__c</fullName>
        <description>EMPLOYED_OR_ADMITTED_HEALTHCARE_TYPE</description>
        <inlineHelpText>Facility type:</inlineHelpText>
        <label>Congregate Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Facility_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IX_Pregnancy_Detail__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Pregnancy Detail</inlineHelpText>
        <label>Imp/Exp Pregnancy Detail</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IX_Underlying_Illness_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Underlying Illness Description</inlineHelpText>
        <label>Imp/Exp Underlying Illness Description</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IX_Underlying_Illness_Specify_Other__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Underlying Illness Specify Other</inlineHelpText>
        <label>Imp/Exp Underlying Illness Specify Other</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IX_Underlying_Illness_Specify__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Underlying Illness Specify</inlineHelpText>
        <label>Imp/Exp Underlying Illness Specify</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Healthcare_Worker__c</fullName>
        <label>Is Healthcare Worker?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Unknown</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Languages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Exposure_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Exposure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Location Name</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Pregnancy_Detail__c</fullName>
        <description>PREGNANT_SPECIFY</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Gestational age (in weeks):</inlineHelpText>
        <label>X-Pregnancy Detail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Input__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Teams</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>X-Underlying Illness Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify_Other__c</fullName>
        <description>Maven Export Report: UNDERLYING_ILLNESS_OTHER_DESC</description>
        <encryptionScheme>None</encryptionScheme>
        <label>X-Underlying Illness Specify Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify__c</fullName>
        <label>X-Underlying Illness Specify</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Underlying_Illness</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Underlying_Illness__c</fullName>
        <description>UNDERLYING_ILLNESS</description>
        <inlineHelpText>Does patient have underlying illness?</inlineHelpText>
        <label>Underlying Illness</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Unknown</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Zip_Code_Input__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact_Outreach</fullName>
        <active>true</active>
        <businessProcess>Contact Tracing</businessProcess>
        <label>Contact Outreach</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location_Outreach</fullName>
        <active>true</active>
        <businessProcess>Contact Tracing</businessProcess>
        <label>Location Outreach</label>
    </recordTypes>
</CustomObject>

CTT_Package/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_is_a_Minor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Contact Object checkbox</description>
        <label>Person is a Minor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Health_Care_Worker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Health Care Worker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_In_Long_Term_Care_Facility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is in congregate setting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language Picklist with global picklist value set</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Languages</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

CTT_Package/objects/Underlying_Illness__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Contact Outreach, Positive Outreach</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Underlying Illnesses</relationshipLabel>
        <relationshipName>Underlying_Illnesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pregnancy_Detail__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Gestational age (in weeks):</inlineHelpText>
        <label>Pregnancy Detail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Underlying Illness Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify_Other__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>If Other, Please Specify</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify__c</fullName>
        <label>Underlying Illness Specify</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Underlying_Illness</valueSetName>
        </valueSet>
    </fields>
    <label>Underlying Illness</label>
    <nameField>
        <displayFormat>UI-{00000000}</displayFormat>
        <label>UI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underlying Illnesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Teams</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

CTT_Package/globalValueSets/Facility_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ASSISTED_LIVING</fullName>
    </customValue>
    <customValue>
        <fullName>BLOOD_BANK</fullName>
    </customValue>
    <customValue>
        <fullName>COMMUNITY_HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CORRECTIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>DIALYSIS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG_TREATMENT</fullName>
    </customValue>
    <customValue>
        <fullName>ER_URGENT</fullName>
    </customValue>
    <customValue>
        <fullName>FAMILY_PLANNING_CLINIC</fullName>
    </customValue>
    <customValue>
        <fullName>GROUP_HOME</fullName>
    </customValue>
    <customValue>
        <fullName>HIV_TESTING</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL_BASED</fullName>
    </customValue>
    <customValue>
        <fullName>INDIAN</fullName>
    </customValue>
    <customValue>
        <fullName>INPATIENT_PSYCHIATRIC</fullName>
    </customValue>
    <customValue>
        <fullName>LABOR_DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>LABORATORY</fullName>
    </customValue>
    <customValue>
        <fullName>LTAC</fullName>
    </customValue>
    <customValue>
        <fullName>LTCF</fullName>
    </customValue>
    <customValue>
        <fullName>MENTAL_HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>MILITARY_VA</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER_FACILITY</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER_HD</fullName>
    </customValue>
    <customValue>
        <fullName>PRENATAL</fullName>
    </customValue>
    <customValue>
        <fullName>PRIVATE_PRACTICE</fullName>
    </customValue>
    <customValue>
        <fullName>STD_CLINIC</fullName>
    </customValue>
    <customValue>
        <fullName>SCHOOL_BASED</fullName>
    </customValue>
    <customValue>
        <fullName>TB_CLINIC</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>Rehab</fullName>
        <isActive>false</isActive>
        <label>Rehab</label>
    </customValue>
    <customValue>
        <fullName>Long-term care facility</fullName>
        <isActive>false</isActive>
        <label>Long-term care facility</label>
    </customValue>
    <masterLabel>Facility Type</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/Languages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Akan</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>American Sign Language</fullName>
    </customValue>
    <customValue>
        <fullName>Amharic</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Aragonese</fullName>
    </customValue>
    <customValue>
        <fullName>Aramaic</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Aymara</fullName>
    </customValue>
    <customValue>
        <fullName>Balinese</fullName>
    </customValue>
    <customValue>
        <fullName>Basque</fullName>
    </customValue>
    <customValue>
        <fullName>Betawi</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnian</fullName>
    </customValue>
    <customValue>
        <fullName>Breton</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Cantonese</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <customValue>
        <fullName>Cherokee</fullName>
    </customValue>
    <customValue>
        <fullName>Chickasaw</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Coptic</fullName>
    </customValue>
    <customValue>
        <fullName>Cornish</fullName>
    </customValue>
    <customValue>
        <fullName>Corsican</fullName>
    </customValue>
    <customValue>
        <fullName>Crimean Tatar</fullName>
    </customValue>
    <customValue>
        <fullName>Croatian</fullName>
    </customValue>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/State.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <customValue>
        <fullName>New Jersey</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Team 1</fullName>
    </customValue>
    <customValue>
        <fullName>Team 2</fullName>
    </customValue>
    <masterLabel>Teams</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/Underlying_Illness.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CARDIAC_DISEASE</fullName>
    </customValue>
    <customValue>
        <fullName>CHRONIC_PULMONARY_DISEASE</fullName>
    </customValue>
    <customValue>
        <fullName>CHRONIC_RENAL_DISEASE_OR_HEMODIALYSIS</fullName>
    </customValue>
    <customValue>
        <fullName>DIABETES</fullName>
    </customValue>
    <customValue>
        <fullName>HYPERTENSION</fullName>
    </customValue>
    <customValue>
        <fullName>IMMUNOCOMPROMISED</fullName>
    </customValue>
    <customValue>
        <fullName>LIVER_DISEASE</fullName>
    </customValue>
    <customValue>
        <fullName>NONE</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
    </customValue>
    <customValue>
        <fullName>PREGNANT</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <masterLabel>Underlying Illness</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/Yes_No_Unknown.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Yes / No / Unknown</masterLabel>
</GlobalValueSet>

CTT_Package/classes/CaseTriggerHandler.cls
/**
 * Case Trigger Handler Class
 *
 * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
 * @since   2020-03-29
 */
public without sharing class CaseTriggerHandler {
    private static List<String> dayPostfixes = new List<String>{'th', 'st', 'nd', 'rd', 'th', 'th', 'th', 'th', 'th', 'th' };
    public static void onBeforeInsert(List<Case> newList)
    {
        copyTeamfromParentToChild(newList);
        FleshOutOutreaches(newList);
    }
    public static void onAfterInsert(Map<Id, Case> newCases) {
        /* Changed method name from syncCongregateSetting to syncHighRiskFieldsToContact 4/16/2020 Alexandria Sanborn*/
        syncHighRiskFieldsToContact(null, newCases);
    }
    public static void onBeforeUpdate(Map<Id, Case> oldCases, Map<Id, Case> newCases){
        updateTeam(oldCases, newCases);
    }
    public static void onAfterUpdate(Map<Id, Case> oldCases, Map<Id, Case> newCases){
        /* Changed method name from syncCongregateSetting to syncHighRiskFieldsToContact 4/16/2020 Alexandria Sanborn*/
        syncHighRiskFieldsToContact(oldCases, newCases);
    }
    public static void updateTeam(Map<Id, Case> oldCases, Map<Id, Case> newCases){
        List<Id> ownerIds = new List<Id>();
        for (Case newCase: newCases.values()){
            ownerIds.add(newCase.OwnerId);
        }
        Map<Id, User> userMap = new Map<Id, User>();
        for (User usr: [select Id, Team__c from User where Id=:ownerIds]){
            userMap.put(usr.Id, usr);
        }
        for (Case newCase: newCases.values()){
            String newUser = String.valueOf(newCase.OwnerId);
            Case oldCase = oldCases.get(newCase.Id);
            String oldUser = String.valueOf(oldCase.OwnerId);
            User usr = userMap.get(newCase.OwnerId);
            
            
            
            if (oldCase.Team__c==Null && oldUser.startsWith('00G') && !(newUser.startsWith('00G'))){
                newCase.Team__c = usr.Team__c;
                
            }
            
        }
    }
    public static void copyTeamfromParentToChild(List<Case> newCases){
        List<Id> pCaseIds = new List<Id>();
        for (Case cs: newCases){
            pCaseIds.add(cs.ParentId);
        }
        Map<Id, Case> pCaseMap = new Map<Id, Case>();
        
        for (Case cs2:[select Team__c from Case where Id=:pCaseIds]){
            pCaseMap.put(cs2.Id, cs2);
        }
        for (Case cs: newCases){
            Case pCase = pCaseMap.get(cs.ParentId);
            
            
            if (cs.ParentId != Null){
                
                cs.Team__c = pCase.Team__c;
            }
            
        }
    }
    public static void FleshOutOutreaches(List<Case> newList)
    {
        Map<Id,RecordType> recTypeMap = new Map<Id,RecordType>( [SELECT Id, Name, DeveloperName FROM RecordType WHERE sObjectType = 'Case'] );
        List<Case> contactOutreachCases = new List<Case>();
        List<Case> locationOutreachCases = new List<Case>();
        for (Case c : newList)
        {
            
           // System.debug('====> recType: ' + recTypeMap.get(c.RecordTypeId).DeveloperName);
            if (recTypeMap.get(c.RecordTypeId).DeveloperName == 'Contact_Outreach')
            {
                contactOutreachCases.add(c);
            }
            else if (recTypeMap.get(c.RecordTypeId).DeveloperName == 'Location_Outreach')
            {
                locationOutreachCases.add(c);
            }
        }
        if (contactOutreachCases.size() > 0)
        {
            FleshOutContactOutreaches(contactOutreachCases);
        }
        if (locationOutreachCases.size() > 0)
        {
            FleshOutLocationOutreaches(locationOutreachCases);
        }
    }
    private class CaseAccountLink
    {
        Account a;
        Case c;
    }
    public static void FleshOutContactOutreaches(List<Case> newList)
    {
        Id personAcctRecTypeId =  [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'][0].Id;
        Id contactOutreachQueueId =  [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'Contact_Outreach_Queue'][0].Id;
        List<Case> processCases = new List<Case>();
        List<Account> newAccounts = new List<Account>();
        List<CaseAccountLink> caseLinks = new List<CaseAccountLink>();
        for (Case c : newList)
        {
            // We need to detect that it is a "Quick Action" case
            if (c.Subject == null && c.ContactId == null && c.AccountId == null)
            {
                String dateStr;
                if (c.Last_Exposure_Date__c == null)
                    dateStr = '(Unknown Date)';
                else
                {
                    // Convert the Date to a DateTime (ugh!) so we can format as a string (double ugh!!)
                    dateStr = DateTime.newInstance(c.Last_Exposure_Date__c, Time.newInstance(12, 0, 0, 0)).format('MMM d')
                                + dayPostfixes[Math.mod(c.Last_Exposure_Date__c.day(), 10)];
                }
                c.Subject = 'Possible Contact: ' + dateStr;
                if (c.Assign_to_Queue__c) c.OwnerId = contactOutreachQueueId; // Assign to Contact Outreach Queue
                // Create new Person Account records
                Account a = new Account();
                a.RecordTypeId = personAcctRecTypeId;
                a.FirstName = c.First_Name__c;
                a.LastName = c.Last_Name__c;
                a.MiddleName = c.Middle_Name__c;
                a.PersonHomePhone = c.Home_Phone__c;
                a.PersonMobilePhone = c.Mobile_Phone__c;
                a.Phone = c.Work_Phone__c;
                a.PersonEmail = c.Email__c;
                a.Language__pc = c.Language__c;
/*                System.debug('====> My User.Id: ' + UserInfo.getUserId());
                if (UserInfo.getUserId() == (Id)'005t0000004HAH7') {
                    System.debug('====> Setting PrimaryLanguage for LC: ' + c.Language__c);
                    a.HealthCloudGA__PrimaryLanguage__pc = c.Language__c;
                }
*/
              //  a.HealthCloudGA__Gender__pc = c.Gender__c;
                a.PersonBirthdate = c.Date_Of_Birth__c;
                a.PersonMailingStreet = c.Street_Input__c;
                a.PersonMailingCity = c.City_Input__c;
                a.PersonMailingState =c.State__c;
                a.PersonMailingPostalCode = c.Zip_Code_Input__c;               
                a.Contact_is_a_Minor__pc = c.Contact_is_a_Minor__c;
                newAccounts.add(a);
                CaseAccountLink ccl = new CaseAccountLink();
                ccl.c = c;
                ccl.a = a;
                caseLinks.add(ccl);
            }
        }
        if (newAccounts.size() > 0)
        {
            insert newAccounts;
            /** @todo  Retry this using PersonContactId instead! */
            // We need the PersonIndivudalId value for the person accounts, so we have to query the account records again. :(
//            Map<Id,Account> accountsMap = new Map<Id,Account>( [SELECT Id, PersonIndividualId FROM Account WHERE Id IN :newAccounts] );
            // Map the new accounts so we can call the @future method below -- the PersonIndividualId is not set yet
            Map<Id,Account> accountsMap = new Map<Id,Account>( newAccounts );
            for (CaseAccountLink ccl : caseLinks)
            {
                ccl.c.AccountId = ccl.a.Id;
            }
            LinkPersonAccountCases(accountsMap.keySet());
        }
    }
    @future
    public static void LinkPersonAccountCases(Set<Id> personAcctIds)
    {
        List<Case> casesToUpdate = [SELECT Id, AccountId, Account.PersonContactId FROM Case WHERE AccountId IN :personAcctIds];
        for (Case c : casesToUpdate)
        {
            c.ContactId = c.Account.PersonContactId;
        }
        update casesToUpdate;
    }
    public static String FormatSubjectDate(Date theDate)
    {
        String dateStr;
        if (theDate == null)
            dateStr = '(Unknown Date)';
        else
        {
            // Convert the Date to a DateTime (ugh!) so we can format as a string (double ugh!!)
            dateStr = DateTime.newInstance(theDate, Time.newInstance(12, 0, 0, 0)).format('MMM d')
                        + dayPostfixes[Math.mod(theDate.day(), 10)];
        }
        return dateStr;        
    }
    public static void FleshOutLocationOutreaches(List<Case> newList)
    {
        System.debug('====> in FleshOutLocationOutreaches()');
        Id businessAcctRecTypeId =  [SELECT Id FROM RecordType WHERE Name = 'Business' and SObjectType = 'Account'][0].Id;
        Id locationOutreachQueueId =  [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'Location_Outreach_Queue'][0].Id;
        List<Case> processCases = new List<Case>();
        List<Account> newAccounts = new List<Account>();
        List<CaseAccountLink> caseLinks = new List<CaseAccountLink>();
        for (Case c : newList)
        {
            if (c.Subject == null)
            {
                String dateStr;
                if (c.Last_Exposure_Date__c == null)
                    dateStr = '(Unknown Date)';
                else
                {
                    // Convert the Date to a DateTime (ugh!) so we can format as a string (double ugh!!)
                    dateStr = DateTime.newInstance(c.Last_Exposure_Date__c, Time.newInstance(12, 0, 0, 0)).format('MMM d')
                                + dayPostfixes[Math.mod(c.Last_Exposure_Date__c.day(), 10)];
                }
                c.Subject = 'Location Visited: ' + dateStr;
            }
            // Assign_to_Queue__c not currently exposed, but defaults to True
            if (c.Assign_to_Queue__c) c.OwnerId = locationOutreachQueueId; // Assign to Location Outreach Queue
            if (c.ContactId == null && c.AccountId == null && c.Location_Name__c != null)
            {
                // Create new Person Account records
                Account a = new Account();
                a.RecordTypeId = businessAcctRecTypeId;
                a.Name = c.Location_Name__c;
//                a.Phone = c.Phone__c;
//                a.Email__c = c.Email__c;
                newAccounts.add(a);
                CaseAccountLink ccl = new CaseAccountLink();
                ccl.c = c;
                ccl.a = a;
                caseLinks.add(ccl);
            }
        }
        if (newAccounts.size() > 0)
        {
            insert newAccounts;
            for (CaseAccountLink ccl : caseLinks)
            {
                ccl.c.AccountId = ccl.a.Id;
            }
        }
    }
    /* Changed method name from syncCongregateSetting to syncHighRiskFieldsToContact 4/16/2020 Alexandria Sanborn*/
    public static void syncHighRiskFieldsToContact(Map<Id, Case> oldCases, Map<Id, Case> newCases) {
        Set<Id> contactIds = new Set<Id>();
        Map<Id, Boolean> congregateSettingMap = new Map<Id, Boolean>();
        /* Added 4/16/2020 Alexandria Sanborn*/
        //start 
        Map<Id, Boolean> healthcareWorkerMap = new Map<Id, Boolean>(); 
        //end
        for (Case c : newCases.values()) {
            if (oldCases!=null &&
                (oldCases.get(c.Id).Employed_or_Admitted_Location_Type__c != c.Employed_or_Admitted_Location_Type__c ||
                oldCases.get(c.Id).ContactId!=c.ContactId)) {
                Boolean congregateFlag = c.Employed_or_Admitted_Location_Type__c!=null ? true : false;
                congregateSettingMap.put(c.ContactId, congregateFlag);
            }
            /* Added 4/16/2020 Alexandria Sanborn*/
            //start
            if (oldCases!=null &&
                (oldCases.get(c.Id).Is_Healthcare_Worker__c != c.Is_Healthcare_Worker__c ||
                oldCases.get(c.Id).ContactId!=c.ContactId)) {
                Boolean healthcareWorkerFlag = c.Is_Healthcare_Worker__c == 'Yes' ? true : false;
                healthcareWorkerMap.put(c.ContactId, healthcareWorkerFlag);
            }
            //end
        }
        List<Contact> contactsToSync = new List<Contact>();
        system.debug(healthcareWorkerMap);
        system.debug(congregateSettingMap);
        if (congregateSettingMap.size() > 0 || healthcareWorkerMap.size() > 0) {
            for (Contact cc : [SELECT Id, Is_In_Long_Term_Care_Facility__c,Is_Health_Care_Worker__c FROM Contact WHERE Id IN :congregateSettingMap.keySet() OR Id IN :healthcareWorkerMap.keySet()]) {
                if(congregateSettingMap.containsKey(cc.Id)){
                    cc.Is_In_Long_Term_Care_Facility__c = congregateSettingMap.get(cc.Id);
                }
                /* Added 4/16/2020 Alexandria Sanborn*/
                //start
                if(healthcareWorkerMap.containsKey(cc.Id)){
                    cc.Is_Health_Care_Worker__c = healthcareWorkerMap.get(cc.Id);
                }
                //end
                contactsToSync.add(cc);
            }
        }
        if (contactsToSync.size() > 0)
            update contactsToSync;
    }

    /**
     * Object specifiers
     * 
     * These can be added or bitwise-OR'ed together to specify more than one object:
     * 
     * objSpec_UnderlyingIllness + objSpec_SomeOtherObject
     * objSpec_UnderlyingIllness | objSpec_SomeOtherObject
     */
    public static Integer objSpec_UnderlyingIllness = 1 << 0;
//    public static Integer objSpec_SomeOtherObject = 1 << 1;
//    public static Integer objSpec_SomeOtherObject = 1 << 2;
//    public static Integer objSpec_SomeOtherObject = 1 << 3;
//    public static Integer objSpec_SomeOtherObject = 1 << 4;
    public static Integer objSpec_ALL = objSpec_UnderlyingIllness; // | objSpec_SomeOtherObject | objSpec_SomeOtherObject

    /**
     * Update export fields from related lists
     * 
     * We have a couple ways we could implement this:
     * 
     * 1) Build separate methods for each of the related objects and call each one separately depending on which related object
     *    is updated. This would work on given that users will be editing one set of related objects at a time. However it means
     *    having separate code for each one. It also doesn't work well if we need to update all related fields at the same time
     *    (which may not ever be needed).
     * 
     * 2) We could build one master method that updates all export fields from all related lists in one go. That would ensure we
     *    have only one query (assuming we query related data through the child object reference field), would provide a minimal
     *    amount of code to maintain, and would be most efficient if we need to update all fields at the same time (which we
     *    aren't sure would ever be needed). However it means we are querying lots of related objects each time we make just one
     *    update.
     * 
     * 3) Build one master method, but be able to specify which related objets need to be loaded. This would be the most efficient
     *    and flexible, and would only require one set of code to maintain, but the code itself could be a lot more complex to
     *    add/remove/execute code just for specific objects.
     * 
     * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
     * @since   2020-04-26
     */
    @future
    public static void UpdateExportFields(Set<Id> caseIds, Integer objectSpecifier)
    {
        // Start the Case query
        String soql = 'SELECT Id ';

        // SOQL sub-query for Underlying_Illness__c related records
        if ((objectSpecifier & objSpec_UnderlyingIllness) != 0) {
            soql += ', (SELECT Underlying_Illness_Specify__c, Underlying_Illness_Specify_Other__c, Underlying_Illness_Description__c, Pregnancy_Detail__c ';
            soql += ' FROM Underlying_Illnesses__r ORDER BY Name)';
        }

        // End the Case query
        soql += ' FROM Case WHERE Id IN :caseIds';

        // Execute the query
        List<Case> cases = Database.query(soql);

        List<Case> updateCases = new List<Case>();

        // Go through each case and build up 'export' fields from the related children records
        for (Case c : cases)
        {
            Case newC = new Case( Id = c.Id );

            // Update export fields for Underlying_Illness__c related records
            if ((objectSpecifier & objSpec_UnderlyingIllness) != 0) {
                newC.IX_Underlying_Illness_Specify__c = ImplodeValues(c.Underlying_Illnesses__r, 'Underlying_Illness_Specify__c');
                newC.IX_Underlying_Illness_Specify_Other__c = ImplodeValues(c.Underlying_Illnesses__r, 'Underlying_Illness_Specify_Other__c');
                newC.IX_Underlying_Illness_Description__c = ImplodeValues(c.Underlying_Illnesses__r, 'Underlying_Illness_Description__c');
                newC.IX_Pregnancy_Detail__c = ImplodeValues(c.Underlying_Illnesses__r, 'Pregnancy_Detail__c');
            }

            updateCases.add(newC);
        }

        update updateCases;
    }

    /**
     * Select and join together all values from a set of records
     * 
     * recs -- a list of sObjects -- can be any object, standard or custom
     * 
     * origField -- this is the field to get from the list of records. This can be a standard field (i.e. 'LastName' from Contacts),
     *              a custom field (i.e. 'Close_Reason__c' for Case), or a field reference (i.e. 'Account.RecordType.Name' for Contacts)
     * 
     * Returns a string value of semi-colon concatenated values from each of the records. Null values will be returned as '', so
     * two records with null values, followed by one record with a value will look like ';;Value3'
     * 
     * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
     * @since   2020-04-26
     */
    public static String ImplodeValues(List<sObject> recs, String origField)
    {
        if (recs.size() == 0)
            return null;
        
        List<String> parts = new List<String>();

        for (sObject rec : recs)
        {
            String field = origField;

            // Handle field references like <Contact>.'Account.RecordType.Name'
            if (field.contains('.'))
            {
                // Split the field reference list up on '.'
                List<String> fieldParts = field.split('\\.');

                // Iterate through all the base reference objects (i.e. 'Account.RecordType' in example from above)
                for (Integer i = 0; i < fieldParts.size()-1; i++)
                {
                    field = fieldParts[i];
                    
                    // Assign rec to 'parent' object
                    rec = rec.getsObject(field);
                }

                // Finally set field to the final (field) part of the referenced field (i.e. 'Name' in example above)
                field = fieldParts[fieldParts.size()-1]; 
            }

            // Get the field from the record
            parts.add((String)(rec.get(field)));
        }

        // Join all resulting parts together with a semi-colon
        return String.join(parts, ';');
    }
}