CTT_Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACN_Care_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Care Team</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Screen_Data_Elements__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Screen</label>
        <referenceTo>ACN_Call_Flow_Screen__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>ACN_Screen_Data_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Screen Data Elements</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Screen Data Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_QuestionniareContainerCtrlTest.cls
@isTest
private class ACN_QuestionniareContainerCtrlTest{
    static testMethod void questionniareContainerCtrl()
    { 
        /*Create Test Data*/
        
        ACN_Call_Flow_Template__c cft = new ACN_Call_Flow_Template__c(Name='test');
        database.insert(cft);
        ACN_Call_Flow_Screen__c cfs = new ACN_Call_Flow_Screen__c(ACN_Call_Flow_Template__c=cft.id);
        database.insert(cfs);
        ACN_Screen_Data_Elements__c sde = new ACN_Screen_Data_Elements__c(ACN_Screen__c=cfs.id);
        database.insert(sde);
        String tid = cft.id;
        system.assert(tid!=null);
        ACN_QuestionniareContainerCtrl.getQuestionDetails(tid);
        ACN_QuestionniareContainerCtrl.getQuestionDetails(null);
        ACN_QuestionniareContainerCtrl.getProgressPathDetails(tid);
        Account acc = new Account(Name='Sample Acc1',ACN_Care_Team__c=true);
        insert acc;
        String paramString='location=\'ACN_Care_Team__c\';age=80;country=India';
        List<ACN_QuestionniareContainerCtrl.extraParameterWrapper> extraParamMap = ACN_QuestionniareContainerCtrl.getAdditionalParams(tid, acc.Id, paramString);
        paramString='location=\'ACN_Care_Team\';age=80;country=India';
        ACN_QuestionniareContainerCtrl.getAdditionalParams(tid, acc.Id, paramString);
        //system.assert(extraParamMap!=null);
        
    }
    
}