CTT_Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACN_Care_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Care Team</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACN_Screen_Number__c</fullName>
        <displayFormat>SN-{000000}</displayFormat>
        <label>Screen Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Sequence_No__c</fullName>
        <label>Stage Sequence No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Question_Repository__c.object
<CustomObject>
    <label>Question Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Repository</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Screen_Data_Elements__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Question_Identifier__c</fullName>
        <displayFormat>QI-{000000}</displayFormat>
        <label>Question Identifier</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ACN_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question/Component</label>
        <referenceTo>ACN_Question_Repository__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>Question_Data_Entry_Data_Retrieval</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACN_Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Screen</label>
        <referenceTo>ACN_Call_Flow_Screen__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>ACN_Screen_Data_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Screen Data Elements</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Screen Data Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_ExpressionComparisionTest.cls
@isTest
private class ACN_ExpressionComparisionTest {
    
    static testMethod void testgetNewTemplateDetails(){
        /* Create test data */
        ACN_Call_Flow_Template__c cft=new ACN_Call_Flow_Template__c(Name='test');
        database.insert(cft);
        ACN_Call_Flow_Screen__c cfs=new ACN_Call_Flow_Screen__c(ACN_Call_Flow_Template__c=cft.id);
        database.insert(cfs);
        ACN_Call_Flow_Screen__c cfsrec=[select id,ACN_Screen_Number__c from ACN_Call_Flow_Screen__c where id=:cfs.id LIMIT 1];
        ACN_ExpressionComparision.getNewTemplateDetails(cfsrec.ACN_Screen_Number__c);
        System.assert(cft.id!= null);
    }
    
    static testMethod void testgetProgressPathDetails(){
        /* Create test data */
        ACN_Call_Flow_Template__c cft1=new ACN_Call_Flow_Template__c(Name='test1');
        database.insert(cft1);
        ACN_Call_Flow_Screen__c cfs1=new ACN_Call_Flow_Screen__c(ACN_Call_Flow_Template__c=cft1.id,ACN_Stage_Sequence_No__c=2,ACN_Stage_Name__c='abcd');
        database.insert(cfs1);
        ACN_Question_Repository__c qrep=new ACN_Question_Repository__c(Name='repository');
        database.insert(qrep);
        ACN_Screen_Data_Elements__c sde1=new ACN_Screen_Data_Elements__c(ACN_Screen__c=cfs1.id,ACN_Question__c=qrep.id);
        database.insert(sde1);
        String tempid=cft1.id;
        ACN_ExpressionComparision.getProgressPathDetails(tempid);
        System.assert(cft1.id!= null);
        
    }
    static testMethod void testgetSaveQuestion(){
        /* Create test data */
        ACN_Call_Flow_Template__c cft2=new ACN_Call_Flow_Template__c(Name='test1');
        insert cft2;
        ACN_Call_Flow_Screen__c cfs2=new ACN_Call_Flow_Screen__c(ACN_Call_Flow_Template__c=cft2.id,ACN_Stage_Sequence_No__c=1,ACN_Stage_Name__c='abcd');
        insert cfs2;
        ACN_Question_Repository__c qrep1=new ACN_Question_Repository__c(Name='Ques1');
        insert qrep1;
        ACN_Screen_Data_Elements__c sde2=new ACN_Screen_Data_Elements__c(ACN_Screen__c=cfs2.Id,ACN_Question__c=qrep1.Id);
        insert sde2;
        ACN_Screen_Data_Elements__c sde2srec=[select id, ACN_Question_Identifier__c from ACN_Screen_Data_Elements__c where id=:sde2.id LIMIT 1];
        Account acc1=new Account(Name='test2');
        insert acc1;
        // System.assert(cft2.id!= null);
        
        List<ACN_QuestionniareContainerCtrl.questionWrapper> listques = new List<ACN_QuestionniareContainerCtrl.questionWrapper>();
        ACN_QuestionniareContainerCtrl.questionWrapper ques = new ACN_QuestionniareContainerCtrl.questionWrapper(sde2srec, 'test','', cft2.Id, true);
        listques.add(ques);
        String jsonString = JSON.serialize(listques);
        List<String> quesResMap=new List<String>(); 
        quesResMap.add(sde2srec.ACN_Question_Identifier__c);
        String paramString='location=\'ACN_Care_Team__c\';age=80;country=India';
        ACN_ExpressionComparision.getAdditionalParams(cft2.Id, acc1.id, paramString);
        paramString='location=\'ACN_Care_Team\';age=80;country=India';
        ACN_ExpressionComparision.getAdditionalParams(cft2.Id, acc1.id, paramString);
        ACN_ExpressionComparision.SaveQuestion(jsonString, quesResMap,'Case',acc1.id,cft2.Id);
        ACN_ExpressionComparision.SaveQuestion(null, quesResMap,'Host',acc1.id,cft2.Id);

    }
}