CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Sequence_No__c</fullName>
        <label>Stage Sequence No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_UpdateCallFlowScreenTest.cls
@isTest(SeeAllData = false)

public class ACN_UpdateCallFlowScreenTest{
    
    static testMethod void testUpdateDefaultAction(){
        /* Create test data */
        ACN_Call_Flow_Template__c cft1=new ACN_Call_Flow_Template__c(Name='test1');
        database.insert(cft1);
        ACN_Call_Flow_Screen__c cfs1=new ACN_Call_Flow_Screen__c(ACN_Call_Flow_Template__c=cft1.id,ACN_Stage_Sequence_No__c=1,ACN_Stage_Name__c='abcd1');
        database.insert(cfs1);
        ACN_Call_Flow_Screen__c cfs2=new ACN_Call_Flow_Screen__c(ACN_Call_Flow_Template__c=cft1.id,ACN_Stage_Sequence_No__c=2,ACN_Stage_Name__c='abcd');
        database.insert(cfs2);
        
        ACN_UpdateCallFlowScreen.updateDefaultAction(cft1.Id);
    }
}