CTT_Package/objects/ACN_Call_Flow_Conducted__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Flow</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Conducted</relationshipLabel>
        <relationshipName>Call_Flow_Conducted</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Call Flow Conducted</relationshipLabel>
        <relationshipName>Call_Flow_Conducted</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Flow Conducted</label>
    <nameField>
        <displayFormat>CFCN={000000000}</displayFormat>
        <label>Call Flow Conducted Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Flow Conducted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACN_Screen_Number__c</fullName>
        <displayFormat>SN-{000000}</displayFormat>
        <label>Screen Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Sequence_No__c</fullName>
        <label>Stage Sequence No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Question_Repository__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Question_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Repository</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Conducted__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Flow Conducted</label>
        <referenceTo>ACN_Call_Flow_Conducted__c</referenceTo>
        <relationshipLabel>Question Response</relationshipLabel>
        <relationshipName>Question_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Question Response</relationshipLabel>
        <relationshipName>Question_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACN_Question_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Question_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACN_Responses__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Responses</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Question Response</relationshipLabel>
        <relationshipName>Question_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QRN-{00000}</displayFormat>
        <label>Question Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Screen_Data_Elements__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Question_Identifier__c</fullName>
        <displayFormat>QI-{000000}</displayFormat>
        <label>Question Identifier</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ACN_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question/Component</label>
        <referenceTo>ACN_Question_Repository__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>Question_Data_Entry_Data_Retrieval</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACN_Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Screen</label>
        <referenceTo>ACN_Call_Flow_Screen__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>ACN_Screen_Data_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Screen Data Elements</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Screen Data Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>HOSPITAL_NAME</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risk_Category__c</fullName>
        <label>Risk Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High Risk</fullName>
                </value>
                <value>
                    <fullName>Medium Risk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

CTT_Package/classes/ACN_ExpressionComparision.cls
// this is Controller class for ACN_QuestionnaireContainer component
public without sharing class ACN_ExpressionComparision { 
    // returns list of questions when there is change in template
    @AuraEnabled
    public static List<ACN_QuestionniareContainerCtrl.questionWrapper> getNewTemplateDetails(String screenNo) {
        try{
            List<ACN_Call_Flow_Screen__c> getNewTemplateId = [SELECT Id, ACN_Call_Flow_Template__c from 
                                                              ACN_Call_Flow_Screen__c 
                                                              where ACN_Screen_Number__c =: screenNo LIMIT 1];
            return ACN_QuestionniareContainerCtrl.getQuestionDetails(getNewTemplateId[0].ACN_Call_Flow_Template__c);
        }
        catch(exception e){
            // System.debug('Exception Occured:: '+e.getMessage());
            return null;
        }
    }
    
    // returns list of questions when there is change in template
    @AuraEnabled
    public static List<ACN_QuestionniareContainerCtrl.extraParameterWrapper> getAdditionalParams(String templateId, String recordId, String paramString){
        /* List<ACN_QuestionniareContainerCtrl.extraParameterWrapper> newAttributes= new List<ACN_QuestionniareContainerCtrl.extraParameterWrapper>();
        newAttributes.add(new ACN_QuestionniareContainerCtrl.extraParameterWrapper('direction','north',templateId));
        newAttributes.add(new ACN_QuestionniareContainerCtrl.extraParameterWrapper('home','3bhk duplex',templateId));
        newAttributes.add(new ACN_QuestionniareContainerCtrl.extraParameterWrapper('vehicle','car;bike',templateId));
        
        System.debug('newAttributes:::: '+newAttributes); */
        try{
        return ACN_QuestionniareContainerCtrl.getAdditionalParams(templateId, recordId, paramString);
        }
        catch(exception e){
            // System.debug('Exception Occured:: '+e.getMessage());
        }
        return null;
    } 
    
    // returns new set of progress paths when template changes.
    @AuraEnabled
    public static Map<Integer, String> getProgressPathDetails(String templateId) {
        try{
            // templateId = 'a1y2a000000cD4KAAU';
            System.debug('templateId:::: '+templateId);
            Map<Integer, String> mapProgressPath = new Map<Integer, String>();
            
            for(ACN_Screen_Data_Elements__c each : [SELECT ACN_Screen__r.ACN_Stage_Sequence_No__c, ACN_Screen__r.ACN_Stage_Name__c FROM ACN_Screen_Data_Elements__c 
                                                    WHERE ACN_Screen__r.ACN_Call_Flow_Template__c =: templateId]) {
                                                        mapProgressPath.put((Integer)each.ACN_Screen__r.ACN_Stage_Sequence_No__c, each.ACN_Screen__r.ACN_Stage_Name__c);
                                                    }
            System.debug('MAP PROGRESS PATH:::: '+mapProgressPath);
            return mapProgressPath;
        }
        catch(exception e){
            // System.debug('Exception Occured:: '+e.getMessage());
            return null;
        }
    }
    // save the ques and the response
    @AuraEnabled
    public static void SaveQuestion(string allQuestionMap , List<String> QuesRespMap, String associationTo, String recordId, String templateId){
        // system.debug('allQuestionMap@@: ' + allQuestionMap);
        // system.debug('QuesRespMap@@: '  + QuesRespMap);
        try {
            List<ACN_QuestionniareContainerCtrl.questionWrapper> wrapperResponse = (List<ACN_QuestionniareContainerCtrl.questionWrapper>)JSON.deserialize(allQuestionMap, List<ACN_QuestionniareContainerCtrl.questionWrapper>.class);
            List<ACN_Question_Response__c> allResponses = new List<ACN_Question_Response__c>();
            ACN_Call_Flow_Conducted__c newFlowConducted = new ACN_Call_Flow_Conducted__c();
            newFlowConducted.ACN_Call_Flow_Template__c = templateId;
            Recordtype caseRT = [select Id, developerName, sobjecttype from Recordtype where developerName='CarePlan' AND SobjectType='Case' LIMIT 1][0];
            Case newCase = new Case(Risk_Category__c='High Risk',Origin='Web-Flow',Priority='High',Subject='COVID-19 Assessment',recordtypeId=caseRT.Id);
/*
            if(associationTo == 'Case'){
                insert newCase;
                newFlowConducted.Case__c = newCase.Id;
            }
*/
            //newFlowConducted.Account__c = recordId;
            insert newFlowConducted;
            for(ACN_QuestionniareContainerCtrl.questionWrapper wrapperRes : wrapperResponse){
                if(QuesRespMap.contains(wrapperRes.eachQuesDetails.ACN_Question_Identifier__c) ){
                    ACN_Question_Response__c eachResponse = new ACN_Question_Response__c();
                    eachResponse.ACN_Call_Flow_Conducted__c = newFlowConducted.Id;
                    eachResponse.ACN_Question_Number__c = wrapperRes.eachQuesDetails.ACN_Question_Identifier__c;
                    eachResponse.ACN_Responses__c = wrapperRes.allResponseDetails;
                    eachResponse.ACN_Call_Flow_Template__c = wrapperRes.eachQuesDetails.ACN_Screen__r.ACN_Call_Flow_Template__c;
                    eachResponse.ACN_Question_Description__c = wrapperRes.eachQuesDetails.ACN_Question__r.ACN_Question_Description__c;
                    if(associationTo == 'Case'){
                        eachResponse.Case__c = newCase.Id;
                    }
                    allResponses.add(eachResponse);
                }           
            }
            insert allResponses;
            // system.debug('allResponses : ' + allResponses);
        }
        catch(exception e){
            // System.debug('Exception Occured:: '+e.getMessage());
        }
    }
}