CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACN_Default_Action_Screen__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Default Action - Screen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACN_Default_Questions__c</fullName>
        <description>Specify which all questions to  be loaded on screen load.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Default Questions</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Layout_Column__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Layout Column Size</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACN_Screen_Logic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Logic</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Screen_Number__c</fullName>
        <displayFormat>SN-{000000}</displayFormat>
        <label>Screen Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ACN_Show_Serial_No__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Serial No</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Sequence_No__c</fullName>
        <label>Stage Sequence No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACN_hasBranching__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Branching</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACN_isEndScreen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>End Screen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACN_isStartScreen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Start Screen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Next__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To Hide the Next button for Compound Screen</description>
        <inlineHelpText>Check this field, Only if you do not want &quot;Next&quot; button in your Compound Screen.</inlineHelpText>
        <label>Hide Next</label>
        <type>Checkbox</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Extra_Parameters__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Extra Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Question_Repository__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Compound_Screen__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Compound Screen</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Options__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Options</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Question_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Compound-Screen</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Datetime</fullName>
                </value>
                <value>
                    <fullName>Multi-select</fullName>
                </value>
                <value>
                    <fullName>Output</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Telephone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Repository</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Screen_Data_Elements__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Default_Answer__c</fullName>
        <description>Default answer to a question, which will be checked by Default when the question is rendered.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Default Answer</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Default_Question__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Specify this question is to be loaded on default screen load.</description>
        <label>Default Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ACN_Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACN_Input_Questions__c</fullName>
        <description>Question Numbers to pass as input to compound screen</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Question/Component Input</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Options_Layout__c</fullName>
        <label>Options Layout</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>one-column</fullName>
                    <default>true</default>
                    <label>1-Column</label>
                </value>
                <value>
                    <fullName>two-column</fullName>
                    <label>2-Column</label>
                </value>
                <value>
                    <fullName>three-column</fullName>
                    <label>3-Column</label>
                </value>
                <value>
                    <fullName>side-by-side</fullName>
                    <label>Side By Side</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ACN_Question_Identifier__c</fullName>
        <displayFormat>QI-{000000}</displayFormat>
        <label>Question Identifier</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ACN_Question_Logic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Display Logic</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question/Component</label>
        <referenceTo>ACN_Question_Repository__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>Question_Data_Entry_Data_Retrieval</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACN_Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Screen</label>
        <referenceTo>ACN_Call_Flow_Screen__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>ACN_Screen_Data_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ACN_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Screen Data Elements</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Screen Data Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_QuestionniareContainerCtrl.cls
public without sharing class ACN_QuestionniareContainerCtrl {
    
    public without sharing class questionWrapper{
        @AuraEnabled
        public ACN_Screen_Data_Elements__c eachQuesDetails{get;set;}
        @AuraEnabled
        public string allResponseDetails{get;set;}
        @AuraEnabled
        public string defaultAnswer{get;set;}
        @AuraEnabled
        public string callFlowTemplateId{get;set;}
        @AuraEnabled
        public Boolean isDefaultQuestion{get;set;}
        /* @AuraEnabled
        public List<questionWrapper> questionWrapper{get;set;}
        @AuraEnabled
        public List<extraParameterWrapper> extraParameterWrapper{get;set;} */
        
        public questionWrapper(ACN_Screen_Data_Elements__c eachQuesDetails, String allResponseDetails, String defaultAnswer, String callFlowTemplateId, Boolean isDefaultQuestion) {
            this.eachQuesDetails = eachQuesDetails;
            this.allResponseDetails = allResponseDetails;
            this.defaultAnswer = defaultAnswer;
            this.callFlowTemplateId = callFlowTemplateId;
            this.isDefaultQuestion = isDefaultQuestion;
        }
        /* public questionWrapper(List<questionWrapper> questionWrapper, List<extraParameterWrapper> extraParameterWrapper){
            this.questionWrapper = questionWrapper;
            this.extraParameterWrapper = extraParameterWrapper;
        } */
    }
    public without sharing class extraParameterWrapper{
        @AuraEnabled
        public String key{get;set;}
        @AuraEnabled
        public String value{get;set;}
        @AuraEnabled
        public String templateId{get;set;}
        
        public extraParameterWrapper(String key, String value, String templateId) {
            this.key = key;
            this.value = value;
            this.templateId = templateId;
        }
    }
    /* public without sharing class QRwrapper{
        @AuraEnabled
        public List<questionWrapper> questionWrapper{get;set;}
        @AuraEnabled
        public List<extraParameterWrapper> extraParameterWrapper{get;set;}
        
        public QRwrapper(List<questionWrapper> questionWrapper, List<extraParameterWrapper> extraParameterWrapper){
            this.questionWrapper = questionWrapper;
            this.extraParameterWrapper = extraParameterWrapper;
        }
    } */
    
    @AuraEnabled
    public static List<questionWrapper> getQuestionDetails(String templateId){
        // templateId = 'a1y2a000000cD4KAAU';
        List<questionWrapper> quesWrapper = new List<questionWrapper>();
        try{
            for(ACN_Screen_Data_Elements__c eachData : [Select Id, Name, ACN_Question_Identifier__c, ACN_Display_Order__c, 
                                                        ACN_Question_Logic__c, ACN_Default_Question__c, ACN_Default_Answer__c,
                                                        ACN_Screen__r.ACN_Screen_Logic__c,ACN_Screen__r.ACN_Screen_Number__c,                                                         
                                                        ACN_Input_Questions__c,ACN_Screen__r.ACN_Default_Action_Screen__c, 
                                                        ACN_Screen__r.ACN_isStartScreen__c, ACN_Screen__r.ACN_isEndScreen__c, ACN_Screen__r.Hide_Next__c,
                                                        ACN_Screen__r.ACN_Default_Questions__c, ACN_Screen__r.ACN_Call_Flow_Template__r.Name,
                                                        ACN_Question__r.Name,ACN_Question__r.ACN_Type__c, ACN_Question__r.ACN_Options__c, 
                                                        ACN_Question__r.ACN_Question_Description__c,
                                                        ACN_Screen__r.ACN_hasBranching__c,ACN_Screen__r.ACN_Stage_Sequence_No__c,
                                                        ACN_Screen__r.ACN_Layout_Column__c,ACN_Options_Layout__c,ACN_Screen__r.ACN_Show_Serial_No__c,
                                                        ACN_Screen__r.ACN_Stage_Name__c,ACN_Question__r.ACN_Compound_Screen__c,ACN_Screen__r.ACN_Call_Flow_Template__r.ACN_Extra_Parameters__c
                                                        FROM ACN_Screen_Data_Elements__c
                                                        WHERE ACN_Screen__r.ACN_Call_Flow_Template__c =: templateId
                                                        Order By ACN_Display_Order__c, ACN_Screen__r.ACN_Stage_Sequence_No__c 
                                                        ASC])
            {
                System.debug('eachData.ACN_Default_Answer__c:::: '+eachData.ACN_Default_Answer__c);
                quesWrapper.add(new questionWrapper(eachData, '', eachData.ACN_Default_Answer__c != null ? eachData.ACN_Default_Answer__c : '', templateId, eachData.ACN_Default_Question__c));
            }
            
            System.debug('quesWrapper:::: '+quesWrapper.size());
            
            return quesWrapper;
        }
        catch(Exception e){
            return null;
        }
    }
    
    
    /* @AuraEnabled
public static questionWrapper getQuestionDetails(String templateId){
// templateId = 'a1y2a000000cD4KAAU';
Boolean hasExtraParams = false;
List<questionWrapper> quesWrapper = new List<questionWrapper>();
try{
for(ACN_Screen_Data_Elements__c eachData : [Select Id, Name, ACN_Question_Identifier__c, ACN_Display_Order__c, 
ACN_Question_Logic__c, ACN_Default_Question__c, 
ACN_Screen__r.ACN_Screen_Logic__c,ACN_Screen__r.ACN_Screen_Number__c,                                                         
ACN_Input_Questions__c,ACN_Screen__r.ACN_Default_Action_Screen__c, 
ACN_Screen__r.ACN_isStartScreen__c, ACN_Screen__r.ACN_isEndScreen__c, ACN_Screen__r.Hide_Next__c,
ACN_Screen__r.ACN_Default_Questions__c, ACN_Screen__r.ACN_Call_Flow_Template__r.Name,
ACN_Question__r.Name,ACN_Question__r.ACN_Type__c, ACN_Question__r.ACN_Options__c, 
ACN_Question__r.ACN_Question_Description__c,
ACN_Screen__r.ACN_hasBranching__c,ACN_Screen__r.ACN_Stage_Sequence_No__c,
ACN_Screen__r.ACN_Layout_Column__c,ACN_Options_Layout__c,ACN_Screen__r.ACN_Show_Serial_No__c,
ACN_Screen__r.ACN_Stage_Name__c,ACN_Question__r.ACN_Compound_Screen__c,ACN_Screen__r.ACN_Call_Flow_Template__r.ACN_Extra_Parameters__c
FROM ACN_Screen_Data_Elements__c
WHERE ACN_Screen__r.ACN_Call_Flow_Template__c =: templateId
Order By ACN_Display_Order__c, ACN_Screen__r.ACN_Stage_Sequence_No__c 
ASC])
{
System.debug('eachData:::: '+eachData.ACN_Screen__r.ACN_Call_Flow_Template__r.ACN_Extra_Parameters__c);
quesWrapper.add(new questionWrapper(eachData, '', templateId, eachData.ACN_Default_Question__c));
if(eachData.ACN_Screen__r.ACN_Call_Flow_Template__r.ACN_Extra_Parameters__c != null){
hasExtraParams = true;
}
}

System.debug('quesWrapper:::: '+quesWrapper.size()+' :::: '+hasExtraParams);

List<extraParameterWrapper> extraParams = new List<extraParameterWrapper>();
if(hasExtraParams){
extraParams= getAdditionalParams(templateId);
}
questionWrapper ques_extraParams = new questionWrapper(quesWrapper,extraParams);

// ques_extraParams(quesWrapper,extraParams);

return ques_extraParams; // quesWrapper;
}
catch(Exception e){
return null;
}
} */
    @AuraEnabled
    public static List<extraParameterWrapper> getAdditionalParams(String templateId, String recordId, String paramString){
        try{
            // paramString='location=\'HealthCloudGA__Age__pc\';age=80;param=india';
            // templateId='temp1';
            String queryString = 'SELECT Id,';
            // recordId = '0012a000004UGyYAAW'; // a1y2a000000cD4KAAU // a1z2a000000KexwAAC
            List<ACN_QuestionniareContainerCtrl.extraParameterWrapper> extraParams = new List<ACN_QuestionniareContainerCtrl.extraParameterWrapper>();
            String[] opertions =  paramString.split(';');
            System.debug('opertions:::: '+opertions);
            for(String ops : opertions){
                String[] operands = ops.split('=');
                queryString += operands[1].startsWith('\'') ? operands[1].removeEnd('\'').removeStart('\'')+',' : '';
                extraParams.add(new ACN_QuestionniareContainerCtrl.extraParameterWrapper(operands[0],operands[1],templateId));
            }
            System.debug('queryString:::: '+queryString);
            System.debug('extraParams1:::: '+extraParams);
            
            String sObjName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();
            
            queryString = queryString.removeEnd(',') + ' FROM ' + sObjName +' WHERE Id =:recordId';
            
            System.debug('queryString:::: '+queryString);
            
            sObject rec = Database.query(queryString);
            
            for(ACN_QuestionniareContainerCtrl.extraParameterWrapper param : extraParams){
                if(param.value.startsWith('\'')){
                    System.debug(rec.get(param.value.removeEnd('\'').removeStart('\'')));
                    param.value = String.valueOf(rec.get(param.value.removeEnd('\'').removeStart('\'')));
                }
            }
            
            System.debug('extraParams2:::: '+extraParams);
            
            return extraParams; // newAttributes;
        }
        catch(Exception e)
        {
            return null;
        }
    }
    
    @AuraEnabled
    public static Map<Integer, String> getProgressPathDetails(String templateId) {
        
        // templateId = 'a1y2a000000cD4KAAU';
        Map<Integer, String> mapProgressPath = new Map<Integer, String>();
        try{
            /* list<ACN_Screen_Data_Elements__c> listAllQues = new list<ACN_Screen_Data_Elements__c>([Select ACN_Screen__r.ACN_Stage_Sequence_No__c, ACN_Screen__r.ACN_Stage_Name__c
                                                                                                   from ACN_Screen_Data_Elements__c 
                                                                                                   where ACN_Screen__r.ACN_Call_Flow_Template__c =: templateId Limit 50000]);
            */
            for(ACN_Screen_Data_Elements__c each : [SELECT ACN_Screen__r.ACN_Stage_Sequence_No__c, ACN_Screen__r.ACN_Stage_Name__c
                                                    FROM ACN_Screen_Data_Elements__c 
                                                    WHERE ACN_Screen__r.ACN_Call_Flow_Template__c =: templateId]) {
                                                        mapProgressPath.put((Integer)each.ACN_Screen__r.ACN_Stage_Sequence_No__c, each.ACN_Screen__r.ACN_Stage_Name__c);
                                                    }
        }
        catch(Exception e)
        {
            return null;
        }
        //System.debug('MAP PROGRESS PATH:::: '+mapProgressPath);
        return mapProgressPath;
    }
    
}