CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_TemplateSelectionCtrlTest.cls
/*test class for ACN_TemplateSelectionCtrl
 * created by : Ashish 
*/

@isTest
public class ACN_TemplateSelectionCtrlTest
{
    @isTest static void testTemplates()
    {
        ACN_Call_Flow_Template__c temp1 = new ACN_Call_Flow_Template__c();
        temp1.Name = 't1';
        database.insert(temp1);
        
        Test.startTest();
        List<ACN_Call_Flow_Template__c> getTemplates = ACN_TemplateSelectionCtrl.getTemplates();
        System.assertEquals(getTemplates, null);
        temp1.ACN_Status__c = 'Active';
        database.update(temp1);
        getTemplates = ACN_TemplateSelectionCtrl.getTemplates();
        System.assertEquals(getTemplates.size(), 1);
        ACN_TemplateSelectionCtrl.getRecordDetails(temp1.Id);
        ACN_TemplateSelectionCtrl.getRecordDetails(null);
        Test.stopTest();
    }
}