CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACN_Default_Action_Screen__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Default Action - Screen</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACN_Screen_Number__c</fullName>
        <displayFormat>SN-{000000}</displayFormat>
        <label>Screen Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ACN_Stage_Sequence_No__c</fullName>
        <label>Stage Sequence No.</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_UpdateCallFlowScreen.cls
/*
@Author : Abhita Bansal
@Description : This class is used to update the Default Action field in Call Flow screen object.
@since   2020-05-03
**/
public class ACN_UpdateCallFlowScreen{
    
    public static List<ACN_Call_Flow_Screen__c> flowList = new List<ACN_Call_Flow_Screen__c>();
    public static List<String> seqList = new List<String>();
    public static Map<String, String> mapSeqToNum = new Map<String, String>();
    public static List<ACN_Call_Flow_Screen__c> updateFlowList = new List<ACN_Call_Flow_Screen__c>();
    
    @AuraEnabled
    public static void updateDefaultAction(Id templateId){
        
        Integer i = 0;
        
        try{
            flowList = [Select Id, ACN_Default_Action_Screen__c, ACN_Stage_Sequence_No__c, ACN_Screen_Number__c 
                            from ACN_Call_Flow_Screen__c where ACN_Call_Flow_Template__c = :templateId ORDER BY ACN_Stage_Sequence_No__c ASC];
            
            
            for(ACN_Call_Flow_Screen__c flowScreen : flowList){
                seqList.add(String.ValueOf(flowScreen.ACN_Stage_Sequence_No__c));
                mapSeqToNum.put(String.ValueOf(flowScreen.ACN_Stage_Sequence_No__c), flowScreen.ACN_Screen_Number__c );
            }
            
            for(ACN_Call_Flow_Screen__c flowScreen : flowList){
                i++;
                if(i<seqList.size()){
                    flowScreen.ACN_Default_Action_Screen__c = mapSeqToNum.get(seqList[i]);
                    updateFlowList.add(flowScreen);
                }
            }
        
            if(!updateFlowList.isEmpty()){
                update updateFlowList;
            }
        }
        catch (Exception e){
            System.debug('Exception Occured:::: '+e.getMessage());
        }
    }   
}