CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ACN_Screen_Logic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Logic</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Screen_Data_Elements__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Question_Logic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Display Logic</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ACN_Screen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Screen</label>
        <referenceTo>ACN_Call_Flow_Screen__c</referenceTo>
        <relationshipLabel>Screen Data Elements</relationshipLabel>
        <relationshipName>ACN_Screen_Data_Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Screen Data Elements</label>
    <nameField>
        <displayFormat>RN-{000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Screen Data Elements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_AutoReplaceTest.cls
@isTest(SeeAllData=true)
private class ACN_AutoReplaceTest {
    public static testMethod void testAutoReplaceTrigger() {
        ACN_Call_Flow_Template__c newTemplate = new ACN_Call_Flow_Template__c();
        newTemplate.Name = 'new Sample Template';
        newTemplate.ACN_Status__c = 'Inactive';
        insert newTemplate;
        
        ACN_Call_Flow_Screen__c newScreen = new ACN_Call_Flow_Screen__c();
        newScreen.Name = 'new Sample Screen';
        newScreen.ACN_Screen_Logic__c = '{(QI-000001 = Yes && QI-000004 = No)=:SN-000001}{(QI-000001 = Yes && QI-000004 = No)=:SN-000003}';
        newScreen.ACN_Call_Flow_Template__c = newTemplate.Id; // 'a1y2a000000cD4KAAU';
        insert newScreen;
        System.debug('NewID:::: '+[SELECT Id, Name, ACN_Screen_Logic__c from ACN_Call_Flow_Screen__c where Id =:newScreen.Id]);
        
        ACN_Screen_Data_Elements__c newDataEle = new ACN_Screen_Data_Elements__c();
        newDataEle.ACN_Question_Logic__c = '{(QI-000001 = Yes && QI-000004 = No)=:QI-000001}{(QI-000001 = Yes && QI-000004 = No)=:QI-000001}';
        newDataEle.ACN_Screen__c = newScreen.Id; // 'a1z2a000000Key1AAC';
        insert newDataEle;
        System.debug('NewID:::: '+[SELECT Id, Name, ACN_Question_Logic__c from ACN_Screen_Data_Elements__c where Id =:newDataEle.Id]);
    }
}