CTT_Package/objects/ACN_Call_Flow_Screen__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Call_Flow_Template__c</fullName>
        <label>Call Flow Template</label>
        <referenceTo>ACN_Call_Flow_Template__c</referenceTo>
        <relationshipLabel>Call Flow Screen</relationshipLabel>
        <relationshipName>Call_Flow_Screen</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Flow Screen</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Screen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/objects/ACN_Call_Flow_Template__c.object
<CustomObject>
    <fields>
        <fullName>ACN_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Call Flow Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Flow Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Flow Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/ACN_templateDeletePreventTest.cls
@isTest
public class ACN_templateDeletePreventTest {
    
    private static testmethod void templateDelPreventTest(){
        List<ACN_Call_Flow_Template__c> listOfTemplate = new List<ACN_Call_Flow_Template__c>();
        
        ACN_Call_Flow_Template__c tmp1 = new ACN_Call_Flow_Template__c();        
        tmp1.Name = 'temp1';
        tmp1.ACN_Status__c = 'Active';
        listOfTemplate.add(tmp1);
        
        ACN_Call_Flow_Template__c tmp2 = new ACN_Call_Flow_Template__c();
        tmp2.Name = 'temp2';
        tmp2.ACN_Status__c = 'Active';
        listOfTemplate.add(tmp2); 
        
        insert listOfTemplate;        
        
        ACN_Call_Flow_Screen__c screenData = new ACN_Call_Flow_Screen__c();
        screenData.ACN_Call_Flow_Template__c = tmp1.Id;
        screenData.Name = 'sc1'; 
        insert screenData;
        
        try{
            Delete listOfTemplate;
            //Delete tmp2;
        }
        catch(Exception ee)
        {}
    }
}