CTT_Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Close_Reason__c</fullName>
        <label>Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All contact outreach contacts collected</fullName>
                </value>
                <value>
                    <fullName>Provided contact outreach guidance</fullName>
                </value>
                <value>
                    <fullName>Referred to other provider</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Isolation completed</fullName>
                </value>
                <value>
                    <fullName>Lost to follow up</fullName>
                </value>
                <value>
                    <fullName>Was never reached</fullName>
                </value>
                <value>
                    <fullName>Contact diagnosed with COVID-19</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Died</fullName>
                </value>
                <value>
                    <fullName>Approved to Return to Work(RTW)</fullName>
                    <label>Approved to Return to Work (RTW)</label>
                </value>
                <value>
                    <fullName>Couldn&apos;t be reached</fullName>
                    <isActive>false</isActive>
                    <label>Couldn&apos;t be reached</label>
                </value>
                <value>
                    <fullName>Death/Deceased</fullName>
                    <isActive>false</isActive>
                    <label>Death/Deceased</label>
                </value>
                <value>
                    <fullName>Existing Case</fullName>
                    <isActive>false</isActive>
                    <label>Existing Case</label>
                </value>
                <value>
                    <fullName>Invalid/Wrong Number</fullName>
                    <isActive>false</isActive>
                    <label>Invalid/Wrong Number</label>
                </value>
                <value>
                    <fullName>Lost to Follow-up</fullName>
                    <isActive>false</isActive>
                    <label>Lost to Follow-up</label>
                </value>
                <value>
                    <fullName>Lost to monitoring</fullName>
                    <isActive>false</isActive>
                    <label>Lost to monitoring</label>
                </value>
                <value>
                    <fullName>Quarantine completed</fullName>
                    <isActive>false</isActive>
                    <label>Quarantine completed</label>
                </value>
                <value>
                    <fullName>Recovered</fullName>
                    <isActive>false</isActive>
                    <label>Recovered</label>
                </value>
                <value>
                    <fullName>Referred to LBoH</fullName>
                    <isActive>false</isActive>
                    <label>Referred to LBoH</label>
                </value>
                <value>
                    <fullName>Refused Interview</fullName>
                    <isActive>false</isActive>
                    <label>Refused Interview</label>
                </value>
                <value>
                    <fullName>Successfully Completed Quarantine</fullName>
                    <isActive>false</isActive>
                    <label>Successfully Completed Quarantine</label>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                    <isActive>false</isActive>
                    <label>Unknown</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employed_or_Admitted_Healthcare__c</fullName>
        <description>EMPLOYED_OR_ADMITTED_HEALTHCARE</description>
        <inlineHelpText>Employed at, admitted to, or visited a healthcare setting?</inlineHelpText>
        <label>Connected to Congregate Setting?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Unknown</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employed_or_Admitted_Location_Type__c</fullName>
        <description>EMPLOYED_OR_ADMITTED_HEALTHCARE_TYPE</description>
        <inlineHelpText>Facility type:</inlineHelpText>
        <label>Congregate Setting Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Facility_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Healthcare_Worker__c</fullName>
        <label>Is Healthcare Worker?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Unknown</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Exposure_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Exposure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Location Name</label>
        <length>140</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Teams</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact_Outreach</fullName>
        <active>true</active>
        <businessProcess>Contact Tracing</businessProcess>
        <label>Contact Outreach</label>
    </recordTypes>
    <recordTypes>
        <fullName>Location_Outreach</fullName>
        <active>true</active>
        <businessProcess>Contact Tracing</businessProcess>
        <label>Location Outreach</label>
    </recordTypes>
    <recordTypes>
        <fullName>Positive_Outreach</fullName>
        <active>true</active>
        <businessProcess>Contact Tracing</businessProcess>
        <label>Positive Outreach</label>
    </recordTypes>
</CustomObject>

CTT_Package/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Health_Care_Worker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Health Care Worker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_In_Long_Term_Care_Facility__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is in congregate setting</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

CTT_Package/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
</CustomObject>

CTT_Package/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Teams</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

CTT_Package/globalValueSets/Facility_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ASSISTED_LIVING</fullName>
    </customValue>
    <customValue>
        <fullName>BLOOD_BANK</fullName>
    </customValue>
    <customValue>
        <fullName>COMMUNITY_HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>CORRECTIONAL</fullName>
    </customValue>
    <customValue>
        <fullName>DIALYSIS</fullName>
    </customValue>
    <customValue>
        <fullName>DRUG_TREATMENT</fullName>
    </customValue>
    <customValue>
        <fullName>ER_URGENT</fullName>
    </customValue>
    <customValue>
        <fullName>FAMILY_PLANNING_CLINIC</fullName>
    </customValue>
    <customValue>
        <fullName>GROUP_HOME</fullName>
    </customValue>
    <customValue>
        <fullName>HIV_TESTING</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPITAL_BASED</fullName>
    </customValue>
    <customValue>
        <fullName>INDIAN</fullName>
    </customValue>
    <customValue>
        <fullName>INPATIENT_PSYCHIATRIC</fullName>
    </customValue>
    <customValue>
        <fullName>LABOR_DELIVERY</fullName>
    </customValue>
    <customValue>
        <fullName>LABORATORY</fullName>
    </customValue>
    <customValue>
        <fullName>LTAC</fullName>
    </customValue>
    <customValue>
        <fullName>LTCF</fullName>
    </customValue>
    <customValue>
        <fullName>MENTAL_HEALTH</fullName>
    </customValue>
    <customValue>
        <fullName>MILITARY_VA</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER_FACILITY</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER_HD</fullName>
    </customValue>
    <customValue>
        <fullName>PRENATAL</fullName>
    </customValue>
    <customValue>
        <fullName>PRIVATE_PRACTICE</fullName>
    </customValue>
    <customValue>
        <fullName>STD_CLINIC</fullName>
    </customValue>
    <customValue>
        <fullName>SCHOOL_BASED</fullName>
    </customValue>
    <customValue>
        <fullName>TB_CLINIC</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <customValue>
        <fullName>Rehab</fullName>
        <isActive>false</isActive>
        <label>Rehab</label>
    </customValue>
    <customValue>
        <fullName>Long-term care facility</fullName>
        <isActive>false</isActive>
        <label>Long-term care facility</label>
    </customValue>
    <masterLabel>Facility Type</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/Teams.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Team 1</fullName>
    </customValue>
    <customValue>
        <fullName>Team 2</fullName>
    </customValue>
    <masterLabel>Teams</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/Yes_No_Unknown.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Yes / No / Unknown</masterLabel>
</GlobalValueSet>

CTT_Package/classes/CaseTriggerHandler_Test.cls
@isTest(SeeAllData = false)
public class CaseTriggerHandler_Test{

    static testMethod void testUpdateTeam() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Case Investigator'];
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@pih.org.invalidtest', Team__c='Team 1');
        insert user1;
        
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Positive_Outreach').getRecordTypeId();
        
        Group g1 = [SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName='Positive_Outreach_Queue'];
        
        Case positiveOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId, OwnerId=g1.Id);
        insert positiveOutreach;
        
        System.debug(positiveOutreach);
        
        Test.startTest();
        
            positiveOutreach.OwnerId=user1.Id;
            update positiveOutreach;
        
        Test.stopTest();
        
        user1 = [SELECT Id, Team__c FROM User WHERE Id = :user1.Id];
        positiveOutreach = [SELECT Id, Team__c FROM Case WHERE Id =: positiveOutreach.Id];
        //System.assertEquals(user1.Team__c, positiveOutreach.Team__c);
    }
    
    static testMethod void testInsertContactOutreach() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Case Investigator'];
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@pih.org.invalidtest', Team__c='Team 1');
        insert user1;
        
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Positive_Outreach').getRecordTypeId();
        Id rtId2 = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Contact_Outreach').getRecordTypeId();
        
        Group g1 = [SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName='Positive_Outreach_Queue'];
        
        Case positiveOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId, OwnerId=g1.Id);
        insert positiveOutreach;
        
        System.debug(positiveOutreach);
                
        positiveOutreach.OwnerId=user1.Id;
        update positiveOutreach;
        
        Test.startTest();
            Case contactOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId2, ParentId=positiveOutreach.Id,
                                            Last_Name__c='Test Contact', First_Name__c='Dave');
            insert contactOutreach;
        Test.stopTest();
        
        user1 = [SELECT Id, Team__c FROM User WHERE Id = :user1.Id];
        contactOutreach = [SELECT Id, Team__c FROM Case WHERE Id =: contactOutreach.Id];
        
        //System.assertEquals(user1.Team__c, contactOutreach.Team__c);
        
    }
    
    static testMethod void testInsertContactOutreachWithLastExposureDate() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Case Investigator'];
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@pih.org.invalidtest', Team__c='Team 1');
        insert user1;
        
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Positive_Outreach').getRecordTypeId();
        Id rtId2 = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Contact_Outreach').getRecordTypeId();
        
        Group g1 = [SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName='Positive_Outreach_Queue'];
        
        Case positiveOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId, OwnerId=g1.Id);
        insert positiveOutreach;
        
        System.debug(positiveOutreach);
                
        positiveOutreach.OwnerId=user1.Id;
        update positiveOutreach;
        
        Test.startTest();
            Case contactOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId2, ParentId=positiveOutreach.Id,
                                            Last_Name__c='Test Contact', First_Name__c='Dave', Last_Exposure_Date__c=Date.today().addDays(-5));
            insert contactOutreach;
        Test.stopTest();
        
        user1 = [SELECT Id, Team__c FROM User WHERE Id = :user1.Id];
        contactOutreach = [SELECT Id, Team__c FROM Case WHERE Id =: contactOutreach.Id];
        
       // System.assertEquals(user1.Team__c, contactOutreach.Team__c);
        
    }
    
    static testMethod void testInsertLocationOutReach() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Case Investigator'];
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@pih.org.invalidtest', Team__c='Team 1');
        insert user1;
        
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Positive_Outreach').getRecordTypeId();
        Id rtId2 = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Location_Outreach').getRecordTypeId();
        
        Group g1 = [SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName='Positive_Outreach_Queue'];
        
        Case positiveOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId, OwnerId=g1.Id);
        insert positiveOutreach;
        
        System.debug(positiveOutreach);
                
        positiveOutreach.OwnerId=user1.Id;
        update positiveOutreach;
        
        Test.startTest();
            Case locationOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId2, ParentId=positiveOutreach.Id,
                                            Location_Name__c='Public Library');
            insert locationOutreach;
        Test.stopTest();
        
        user1 = [SELECT Id, Team__c FROM User WHERE Id = :user1.Id];
        locationOutreach = [SELECT Id, Team__c FROM Case WHERE Id =: locationOutreach.Id];
        
        //System.assertEquals(user1.Team__c, locationOutreach.Team__c);
        
    }
    
    static testMethod void testInsertLocationOutReachWithLastExposureDate() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Case Investigator'];
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@pih.org.invalidtest', Team__c='Team 1');
        insert user1;
        
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Positive_Outreach').getRecordTypeId();
        Id rtId2 = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Location_Outreach').getRecordTypeId();
        
        Group g1 = [SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName='Positive_Outreach_Queue'];
        
        Case positiveOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId, OwnerId=g1.Id);
        insert positiveOutreach;
        
        System.debug(positiveOutreach);
                
        positiveOutreach.OwnerId=user1.Id;
        update positiveOutreach;
        
        Test.startTest();
            Case locationOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId2, ParentId=positiveOutreach.Id,
                                            Location_Name__c='Public Library', Last_Exposure_Date__c=Date.today().addDays(-5));
            insert locationOutreach;
        Test.stopTest();
        
        user1 = [SELECT Id, Team__c FROM User WHERE Id = :user1.Id];
        locationOutreach = [SELECT Id, Team__c FROM Case WHERE Id =: locationOutreach.Id];
        
        //System.assertEquals(user1.Team__c, locationOutreach.Team__c);
        
    }

    static testMethod void testSyncCongregateSetting() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Case Investigator'];
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@pih.org.invalidtest', Team__c='Team 1');
        insert user1;
        
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Positive_Outreach').getRecordTypeId();
        
        Group g1 = [SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName='Positive_Outreach_Queue'];
        
        Id personAccountRtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        
        Account acc = new Account(FirstName='Robert', LastName='Browning', RecordTypeId=personAccountRtId);
        insert acc;

        Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];

        Case positiveOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId, OwnerId=g1.Id, ContactId=con.Id);
        insert positiveOutreach;
        
        System.debug(positiveOutreach);
        
        Test.startTest();
            
            positiveOutreach.Employed_or_Admitted_Healthcare__c = 'Yes';
            positiveOutreach.Employed_or_Admitted_Location_Type__c = 'ASSISTED_LIVING';
            update positiveOutreach;
        
        Test.stopTest();
        positiveOutreach = [SELECT Id, Contact.Is_In_Long_Term_Care_Facility__c FROM Case WHERE Id =: positiveOutreach.Id];
        
       // System.assertEquals(true, positiveOutreach.Contact.Is_In_Long_Term_Care_Facility__c);
    }
    
    static testMethod void testSyncHealthcareWorkerSetting() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Case Investigator'];
        
        User user1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser1@pih.org.invalidtest', Team__c='Team 1');
        insert user1;
        
        Id rtId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Positive_Outreach').getRecordTypeId();
        
        Group g1 = [SELECT Id FROM Group WHERE Type='Queue' AND DeveloperName='Positive_Outreach_Queue'];
        Id personAccountRtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        
        Account acc = new Account(FirstName='Robert', LastName='Browning', RecordTypeId=personAccountRtId);
        insert acc;

        Contact con = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];

        Case positiveOutreach = new Case(Status='New', Origin='Phone', RecordTypeId=rtId, OwnerId=g1.Id, ContactId=con.Id);
        insert positiveOutreach;
        
        System.debug(positiveOutreach);
        
        Test.startTest();
        
            positiveOutreach.Is_Healthcare_Worker__c = 'Yes';
            update positiveOutreach;
        
        Test.stopTest();
        positiveOutreach = [SELECT Id, Contact.Is_Health_Care_Worker__c FROM Case WHERE Id =: positiveOutreach.Id];
        
       // System.assertEquals(true, positiveOutreach.Contact.Is_Health_Care_Worker__c);
    }


    /**
     * Test method for CaseTriggerHandler.ImplodeValues()
     * 
     * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
     * @since   2020-04-26
     */
    static testMethod void testImplodeValues()
    {
        //
        // Try with Contacts - OOB Field
        //
        List<Contact> recs1 = new List<Contact>();

        recs1.add(new Contact(LastName = 'A'));
        recs1.add(new Contact(LastName = 'B'));
        recs1.add(new Contact(LastName = 'C'));

        //System.assertEquals('A;B;C', CaseTriggerHandler.ImplodeValues(recs1, 'LastName'));

        
        //
        // Try with Cases - Custom Field
        //
        List<Case> recs2 = new List<Case>();

        recs2.add(new Case(Close_Reason__c = 'Aaa'));
        recs2.add(new Case(Close_Reason__c = 'Bbb'));
        recs2.add(new Case(Close_Reason__c = 'Ccc'));

        System.assertEquals('Aaa;Bbb;Ccc', CaseTriggerHandler.ImplodeValues(recs2, 'Close_Reason__c'));


        //
        // Try with Users -- using field references -- have to do a real query here. We should always have three Sys Admins, so query for those user records
        //
        List<User> recs3 = [SELECT Profile.Name FROM User WHERE Profile.Name = 'System Administrator' LIMIT 3];

        //System.assertEquals('System Administrator;System Administrator;System Administrator', CaseTriggerHandler.ImplodeValues(recs3, 'Profile.Name'));


        //
        // Confirm null values are handled correctly
        //
        List<Case> recs4 = new List<Case>();

        recs4.add(new Case(Close_Reason__c = 'Aaa'));
        recs4.add(new Case(Close_Reason__c = null));
        recs4.add(new Case(Close_Reason__c = 'Ccc'));

        //System.assertEquals('Aaa;;Ccc', CaseTriggerHandler.ImplodeValues(recs4, 'Close_Reason__c'));
    }
}