CTT_Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Disease_Status__c</fullName>
        <description>DISEASE_STATUS</description>
        <inlineHelpText>Disease classification status:</inlineHelpText>
        <label>Disease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maven_Contact_Id__c</fullName>
        <description>Source system ID of Contact/Case</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Enterprise Id</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

CTT_Package/objects/Maven_Staging_Table__c.object
<CustomObject>
    <fields>
        <fullName>Disease_Status__c</fullName>
        <label>Disease Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Value1</fullName>
                    <isActive>false</isActive>
                    <label>Value1</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maven_Contact_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Maven Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Maven Staging Table</label>
    <nameField>
        <displayFormat>MST-{000000}</displayFormat>
        <label>Maven Staging Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maven Staging Table Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/MavenStagingTableTriggerHandler_Test.cls
@IsTest
private class MavenStagingTableTriggerHandler_Test {
    private static testMethod void testMavenStagingTableTriggerHandler() {
        Maven_Staging_Table__c mst = new Maven_Staging_Table__c();

        mst.Maven_Contact_Id__c = '123456';
        mst.First_Name__c = 'Test';
        mst.Last_Name__c = 'Tester';
      	mst.Disease_Status__c = 'CONTACT';
            
        Test.startTest();

        insert mst;

        // Execute @futures
        Test.stopTest();

        List<Case> cases = [SELECT Id, AccountId, ContactId FROM Case WHERE Maven_Contact_Id__c = :mst.Maven_Contact_Id__c];
        System.assertNotEquals(null, cases);
        System.assertEquals(1, cases.size());
        System.assertNotEquals(null, cases[0].AccountId);
        System.assertNotEquals(null, cases[0].ContactId);
    }
    
    private static testMethod void testMavenStagingTableTriggerHandlerConfirmed() {
        Maven_Staging_Table__c mst = new Maven_Staging_Table__c();

        mst.Maven_Contact_Id__c = '123456';
        mst.First_Name__c = 'Test';
        mst.Last_Name__c = 'Tester';
      	mst.Disease_Status__c = 'CONFIRMED';
            
        Test.startTest();

        insert mst;

        // Execute @futures
        Test.stopTest();

        List<Case> cases = [SELECT Id, AccountId, ContactId FROM Case WHERE Maven_Contact_Id__c = :mst.Maven_Contact_Id__c];
        System.assertNotEquals(null, cases);
        System.assertEquals(1, cases.size());
        System.assertNotEquals(null, cases[0].AccountId);
        System.assertNotEquals(null, cases[0].ContactId);
    }
}