CTT_Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IX_Pregnancy_Detail__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Pregnancy Detail</inlineHelpText>
        <label>Imp/Exp Pregnancy Detail</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IX_Underlying_Illness_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Underlying Illness Description</inlineHelpText>
        <label>Imp/Exp Underlying Illness Description</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IX_Underlying_Illness_Specify_Other__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Underlying Illness Specify Other</inlineHelpText>
        <label>Imp/Exp Underlying Illness Specify Other</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IX_Underlying_Illness_Specify__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Import/Export value for Underlying Illness Specify</inlineHelpText>
        <label>Imp/Exp Underlying Illness Specify</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pregnancy_Detail__c</fullName>
        <description>PREGNANT_SPECIFY</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Gestational age (in weeks):</inlineHelpText>
        <label>X-Pregnancy Detail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Count__c</fullName>
        <inlineHelpText>Number of Underlying Illness records</inlineHelpText>
        <label>Underlying Illness Count</label>
        <summaryForeignKey>Underlying_Illness__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>X-Underlying Illness Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify_Other__c</fullName>
        <description>Maven Export Report: UNDERLYING_ILLNESS_OTHER_DESC</description>
        <encryptionScheme>None</encryptionScheme>
        <label>X-Underlying Illness Specify Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify__c</fullName>
        <label>X-Underlying Illness Specify</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Underlying_Illness</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Underlying_Illness__c</fullName>
        <description>UNDERLYING_ILLNESS</description>
        <inlineHelpText>Does patient have underlying illness?</inlineHelpText>
        <label>Underlying Illness</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No_Unknown</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

CTT_Package/objects/Underlying_Illness__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Contact Outreach, Positive Outreach</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Underlying Illnesses</relationshipLabel>
        <relationshipName>Underlying_Illnesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pregnancy_Detail__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Gestational age (in weeks):</inlineHelpText>
        <label>Pregnancy Detail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Underlying Illness Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify_Other__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>If Other, Please Specify</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Underlying_Illness_Specify__c</fullName>
        <label>Underlying Illness Specify</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Underlying_Illness</valueSetName>
        </valueSet>
    </fields>
    <label>Underlying Illness</label>
    <nameField>
        <displayFormat>UI-{00000000}</displayFormat>
        <label>UI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underlying Illnesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/globalValueSets/Underlying_Illness.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CARDIAC_DISEASE</fullName>
    </customValue>
    <customValue>
        <fullName>CHRONIC_PULMONARY_DISEASE</fullName>
    </customValue>
    <customValue>
        <fullName>CHRONIC_RENAL_DISEASE_OR_HEMODIALYSIS</fullName>
    </customValue>
    <customValue>
        <fullName>DIABETES</fullName>
    </customValue>
    <customValue>
        <fullName>HYPERTENSION</fullName>
    </customValue>
    <customValue>
        <fullName>IMMUNOCOMPROMISED</fullName>
    </customValue>
    <customValue>
        <fullName>LIVER_DISEASE</fullName>
    </customValue>
    <customValue>
        <fullName>NONE</fullName>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
    </customValue>
    <customValue>
        <fullName>PREGNANT</fullName>
    </customValue>
    <customValue>
        <fullName>UNKNOWN</fullName>
    </customValue>
    <masterLabel>Underlying Illness</masterLabel>
</GlobalValueSet>

CTT_Package/globalValueSets/Yes_No_Unknown.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Yes / No / Unknown</masterLabel>
</GlobalValueSet>

CTT_Package/classes/UnderlyingIllnessTriggerHandler_Test2.cls
/**
 * Underlying_Illness__c Trigger Handler Class -- with setup method so we get two execution contexts so we get two @future executions
 *
 * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
 * @since   2020-04-27
 */
@IsTest
private class UnderlyingIllnessTriggerHandler_Test2 {

    /**
     * Setup the data
     * 
     * @future method should get executed after this method exits, so all the Case.IX_Underlying_Illness__c fields should get populated
     * and we can test secondary functionality like 'delete' trigger execution
     *
     * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
     * @since   2020-04-27
     */
    @testSetup
    private static void setupData()
    {
        List<Underlying_Illness__c> uis = new List<Underlying_Illness__c>();

        //
        // Insert a Case
        //
        Case c = new Case();
        c.Subject = 'Test Case';
        insert c;
        
        c.Underlying_Illness__c = 'Yes';
        update c;

        //
        // Insert one Underlying Illness record
        //
        Underlying_Illness__c ui1 = new Underlying_Illness__c();
        ui1.Case__c = c.Id;
        ui1.Underlying_Illness_Specify__c = 'CARDIAC_DISEASE';
        ui1.Underlying_Illness_Description__c = 'Bad ticker!';
        uis.add(ui1);

        Underlying_Illness__c ui2 = new Underlying_Illness__c();
        ui2.Case__c = c.Id;
        ui2.Underlying_Illness_Specify__c = 'PREGNANT';
        ui2.Underlying_Illness_Description__c = 'Twins';
        ui2.Pregnancy_Detail__c = '22 wks';
        uis.add(ui2);
        
        Underlying_Illness__c ui3 = new Underlying_Illness__c();
        ui3.Case__c = c.Id;
        ui3.Underlying_Illness_Specify__c = 'OTHER';
        ui3.Underlying_Illness_Specify_Other__c = 'Asthma';
        ui3.Underlying_Illness_Description__c = 'Daily inhaler';
        uis.add(ui3);
        
        insert uis;

        // @future method should get executed after this method exits, so all the Case.IX_Underlying_Illness__c fields should get populated
    }

    /**
     * Test update of one of the records
     *
     * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
     * @since   2020-04-27
     */
    private static testMethod void testUnderlyingIllness_Update()
    {
        List<Underlying_Illness__c> uis = [SELECT Id, Case__c FROM Underlying_Illness__c];
        System.assertNotEquals(null, uis);
        System.assertEquals(3, uis.size());

        //
        // Confirm the record was setup correctly and all the IX_* fields were populated
        //
        List<Case> cases = [SELECT Id,
                                   Underlying_Illness_Count__c,
                                   IX_Underlying_Illness_Specify__c,
                                   IX_Underlying_Illness_Specify_Other__c,
                                   IX_Underlying_Illness_Description__c,
                                   IX_Pregnancy_Detail__c
                            FROM Case
                            WHERE Id = :uis[0].Case__c];
        System.assertNotEquals(null, cases);
        System.assertEquals(1, cases.size());
        System.assertEquals(3, cases[0].Underlying_Illness_Count__c);
        System.assertEquals('CARDIAC_DISEASE;PREGNANT;OTHER', cases[0].IX_Underlying_Illness_Specify__c);
        System.assertEquals(';;Asthma', cases[0].IX_Underlying_Illness_Specify_Other__c);
        System.assertEquals('Bad ticker!;Twins;Daily inhaler', cases[0].IX_Underlying_Illness_Description__c);
        System.assertEquals(';22 wks;', cases[0].IX_Pregnancy_Detail__c);

        //
        // Now, the real test... try deleting one of the Underlying_Illness__c records
        //
        Test.startTest();

        uis[2].Underlying_Illness_Description__c = 'Uses inhaler twice daily';

        update uis[2];

        Test.stopTest(); // fire @future methods

        //
        // Confirm the case fields were updated correctly
        //
        cases = [SELECT Id,
                        Underlying_Illness_Count__c,
                        IX_Underlying_Illness_Specify__c,
                        IX_Underlying_Illness_Specify_Other__c,
                        IX_Underlying_Illness_Description__c,
                        IX_Pregnancy_Detail__c
                 FROM Case
                 WHERE Id = :uis[0].Case__c];
        System.assertNotEquals(null, cases);
        System.assertEquals(1, cases.size());
        System.assertEquals(3, cases[0].Underlying_Illness_Count__c);
        System.assertEquals('CARDIAC_DISEASE;PREGNANT;OTHER', cases[0].IX_Underlying_Illness_Specify__c);
        System.assertEquals(';;Asthma', cases[0].IX_Underlying_Illness_Specify_Other__c);
        System.assertEquals('Bad ticker!;Twins;Uses inhaler twice daily', cases[0].IX_Underlying_Illness_Description__c);
        System.assertEquals(';22 wks;', cases[0].IX_Pregnancy_Detail__c);
    }

    /**
     * Test with deletion of one of the records
     *
     * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
     * @since   2020-04-27
     */
    private static testMethod void testUnderlyingIllness_Delete()
    {
        List<Underlying_Illness__c> uis = [SELECT Id, Case__c FROM Underlying_Illness__c];
        System.assertNotEquals(null, uis);
        System.assertEquals(3, uis.size());

        //
        // Confirm the record was setup correctly and all the IX_* fields were populated
        //
        List<Case> cases = [SELECT Id,
                                   Underlying_Illness_Count__c,
                                   IX_Underlying_Illness_Specify__c,
                                   IX_Underlying_Illness_Specify_Other__c,
                                   IX_Underlying_Illness_Description__c,
                                   IX_Pregnancy_Detail__c
                            FROM Case
                            WHERE Id = :uis[0].Case__c];
        System.assertNotEquals(null, cases);
        System.assertEquals(1, cases.size());
        System.assertEquals(3, cases[0].Underlying_Illness_Count__c);
        System.assertEquals('CARDIAC_DISEASE;PREGNANT;OTHER', cases[0].IX_Underlying_Illness_Specify__c);
        System.assertEquals(';;Asthma', cases[0].IX_Underlying_Illness_Specify_Other__c);
        System.assertEquals('Bad ticker!;Twins;Daily inhaler', cases[0].IX_Underlying_Illness_Description__c);
        System.assertEquals(';22 wks;', cases[0].IX_Pregnancy_Detail__c);

        //
        // Now, the real test... try deleting one of the Underlying_Illness__c records
        //
        Test.startTest();

        delete uis[1];

        Test.stopTest(); // fire @future methods

        //
        // Confirm the case fields were updated correctly
        //
        cases = [SELECT Id,
                        Underlying_Illness_Count__c,
                        IX_Underlying_Illness_Specify__c,
                        IX_Underlying_Illness_Specify_Other__c,
                        IX_Underlying_Illness_Description__c,
                        IX_Pregnancy_Detail__c
                 FROM Case
                 WHERE Id = :uis[0].Case__c];
        System.assertNotEquals(null, cases);
        System.assertEquals(1, cases.size());
        System.assertEquals(2, cases[0].Underlying_Illness_Count__c);
        System.assertEquals('CARDIAC_DISEASE;OTHER', cases[0].IX_Underlying_Illness_Specify__c);
        System.assertEquals(';Asthma', cases[0].IX_Underlying_Illness_Specify_Other__c);
        System.assertEquals('Bad ticker!;Daily inhaler', cases[0].IX_Underlying_Illness_Description__c);
        System.assertEquals(';', cases[0].IX_Pregnancy_Detail__c);
    }
}