CTT_Package/objects/Exposed_Contact_Review__c.object
<CustomObject>
    <description>This Object has all the necessary Details of Contacts Exposed to Positive Cases.</description>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>It takes in the Last Name of the Contact</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Exposed Contact For Review</label>
    <nameField>
        <displayFormat>ECR-{0000}</displayFormat>
        <label>Exposed Contact Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exposed Contact For Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CTT_Package/classes/TriggerFrameworkTest.cls
@isTest
public with sharing class TriggerFrameworkTest {
    
    public static Profile getProfileInfo(String profileName) {
        Profile profileInfo = [SELECT Id, Name FROM Profile WHERE Name=:profileName];
        return profileInfo;
    }
    
    public static testmethod void testConfigEnabledBeforeInsert() {        
		insert new Account(Name='foobar');
    }
    
    public static testmethod void testConfigEnabledBeforeUpdate() {
        Account newAccount = new Account(Name='foobar');
        insert newAccount;
        newAccount.Name = 'foo';
        update newAccount;
    }	
    
    public static testmethod void testConfigEnabledBeforeDelete() {        
        Account newAccount = new Account(Name='foobar');
        insert newAccount;
        delete newAccount;
    }       
    
    public static testmethod void testConfigEnabledAfterUnDelete() {        
        Account newAccount = new Account(Name='foobar');
        insert newAccount;
        delete newAccount;
        undelete newAccount;
    }
    
    @isTest
    public static void testGetRecursionDepth() {
        Test.startTest();
        TriggerFramework.Context obj = new TriggerFramework.Context(new List<Account>(), new List<Account>(), new Map<Id, Account>(), 
                                                                    new Map<Id, Account>(), true, false, false, true, false, true, false);
        obj.enterObject();
        obj.getRecursionDepth();
        obj.beginTrans();
        obj.rollbackTrans();
        Test.stopTest();
    }
    
    
     @isTest
    public static void testInsertExposedContactReview() {
        Test.startTest();
        Exposed_Contact_Review__c obj = new Exposed_Contact_Review__c ();
        obj.last_name__c = 'testLastName';
            insert obj;
        Test.stopTest();
    }
    
    
}