CTT_Package/objects/TriggerFrameworkConfig__mdt.object
<CustomObject>
    <description>Stores the Trigger Framework Configurations</description>
    <fields>
        <fullName>Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disabled records are equivalent to Deleted records. As we can&apos;t delete Metadata types, make them to Disabled.</description>
        <inlineHelpText>Disabled records are equivalent to Deleted records</inlineHelpText>
        <label>Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HandlerClass_ExecutionOrder__c</fullName>
        <description>Used to define order in which the Apex trigger handler classes should be executed</description>
        <inlineHelpText>(Number) Order in which the Apex trigger handler classes should be executed (Ex. 1)</inlineHelpText>
        <label>Handler Class Execution Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_ReEntry__c</fullName>
        <label>Max ReEntry</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Event__c</fullName>
        <label>Trigger Event</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_New_Transaction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use New Transaction</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Framework Config</label>
    <pluralLabel>Trigger Framework Configs</pluralLabel>
</CustomObject>

CTT_Package/objects/TriggerFrameworkProfile__mdt.object
<CustomObject>
    <description>Stores the Trigger Framework Profiles data</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Profile Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Trigger Framework Profile</label>
    <pluralLabel>Trigger Framework Profiles</pluralLabel>
</CustomObject>

CTT_Package/objects/TriggerFrameworkProfileConfig__mdt.object
<CustomObject>
    <description>Junction object between Profile, Config</description>
    <fields>
        <fullName>Config__c</fullName>
        <label>Config</label>
        <referenceTo>TriggerFrameworkConfig__mdt</referenceTo>
        <relationshipLabel>Trigger Framework Profile Configs</relationshipLabel>
        <relationshipName>Trigger_Framework_Profile_Configs</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disabled records are equivalent to Deleted records. As we can&apos;t delete Metadata types, make them to Disabled.</description>
        <inlineHelpText>Disabled records are equivalent to Deleted records</inlineHelpText>
        <label>Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <referenceTo>TriggerFrameworkProfile__mdt</referenceTo>
        <relationshipLabel>Trigger Framework Profile Configs</relationshipLabel>
        <relationshipName>Trigger_Framework_Profile_Configs</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Trigger Framework Profile Config</label>
    <pluralLabel>Trigger Framework Profile Configs</pluralLabel>
</CustomObject>

CTT_Package/classes/TriggerFrameworkUpsertMDT.cls
/*
-----------------------------------------------------------------------------------------------------------------------------------
Author: Nagendra Chinchinada
Description: To create,update Custom Metata Data Types records
Created Date: 05/15/2019
-----------------------------------------------------------------------------------------------------------------------------------
*/
public with sharing class TriggerFrameworkUpsertMDT { 
    /*
-----------------------------------------------------------------------------------------------------------------------------------
Method: upsertMDT
Description: Method to create,update Custom Metata Data Types records
Parameters : mtdObjetAPIName - Object API Name
cmdRecords - List of meta data records of type mtdObjetAPIName in the form of CustomMetadataType wrapper class
-----------------------------------------------------------------------------------------------------------------------------------
*/
    public static string upsertMDT(String mtdObjetAPIName, List<CustomMetadataType> cmdRecords){
        String jobId='';
        List<Metadata.CustomMetadata> customMetadataList =  new List<Metadata.CustomMetadata>();        
        try{
            for (CustomMetadataType metadataRecord : cmdRecords) {
                Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
                String recordDevName = metadataRecord.label.replaceAll(' ', '_'); 
                
                customMetadata.fullName = mtdObjetAPIName+'.' + recordDevName;
                customMetadata.label = metadataRecord.label;
                
                // Add all the field values
                Metadata.CustomMetadataValue customField;
                for(MDTFieldValue fieldValue : metadataRecord.fieldValues) {
                    system.debug('fieldValue: '+fieldValue);
                    customField = new Metadata.CustomMetadataValue();
                    customField.field = fieldValue.field;
                    customField.value = fieldValue.value;
                    customMetadata.values.add(customField);
                }
                customMetadataList.add(customMetadata);            
            }  
            
            
            // Setup deploy callback, MyDeployCallback implements the Metadata.DeployCallback interface 
            TriggerFrameworkMDTCallback callback = new TriggerFrameworkMDTCallback();
            
            //Deploy metadata 
            //If there are morethan 1 records to deploy, will be deployed one by one
            for(Metadata.CustomMetadata customMetadata : customMetadataList){
                Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
                mdContainer.addMetadata(customMetadata);
                System.debug('customMetadata -------------- '+customMetadata);
                // Enqueue custom metadata deployment, jobId is the deployment ID
                String jobIdSingle = Metadata.Operations.enqueueDeployment(mdContainer, callback);
                jobId += jobIdSingle+',';
                
            }
            
        }catch(Exception ex){
            ex.getMessage();
            System.debug('error in upsertMDT -- '+ex.getStackTraceString());
        }
        jobId = jobId.removeEnd(',');
        return jobId;
    }
    
    /**
* @description : Method to insert/update TriggerFrameworkProfile__mdt records
* @author : Nagendra Chinchinada | 6/10/2019
* @param  : TriggerFrameworkProfile__mdt records to be inserted/updated
* @return : Metadata records Deployment JobId as a string
*/
    public static string upsertProfile(TriggerFrameworkProfile__mdt profileRecord){
        Integer maxSize = 40;
        String profileName;
       
        CustomMetadataType metadataRecord = new CustomMetadataType();
        List<MDTFieldValue> mdtValues = new List<MDTFieldValue>();
        if(profileRecord.DeveloperName.length()>maxSize){
            profileName = profileRecord.DeveloperName.substring(0, maxSize);
            metadataRecord.label = removeSpclCharsForCustomMD(profileName);
        }
        else{
            //metadataRecord.DeveloperName = profileRecord.DeveloperName;
            metadataRecord.label = removeSpclCharsForCustomMD(profileRecord.DeveloperName);
        }
        if(String.isNotBlank(profileRecord.Profile_Id__c)){
            mdtValues.add(new MDTFieldValue('Profile_Id__c',profileRecord.Profile_Id__c));
            //mdtValues.add(new MDTFieldValue('DeveloperName',profileRecord.DeveloperName)); 
        }           
        if(profileRecord.Active__c <> null)
            mdtValues.add(new MDTFieldValue('Active__c',profileRecord.Active__c));
        metadataRecord.fieldValues = mdtValues;
        
        return upsertMDT('TriggerFrameworkProfile__mdt', new List<CustomMetadataType>{metadataRecord});
    }
    
    public static string upsertConfig(List<TriggerFrameworkConfig__mdt> configList){
        List<CustomMetadataType> customMetadataTypes = new List<CustomMetadataType>();
        List<MDTFieldValue> fieldValuesList = new List<MDTFieldValue>();
        for(TriggerFrameworkConfig__mdt configRec : configList){
            CustomMetadataType metadataRecord = new CustomMetadataType();
            //metadataRecord.label = configRec.Trigger_Event__c+'_'+configRec.DeveloperName;
            metadataRecord.label = configRec.DeveloperName;
            fieldValuesList.clear();
            //fieldValuesList.add(new MDTFieldValue('Id',configRec.Id));
            //fieldValuesList.add(new MDTFieldValue('DeveloperName',configRec.DeveloperName));
            fieldValuesList.add(new MDTFieldValue('Object_Name__c',configRec.Object_Name__c));
            fieldValuesList.add(new MDTFieldValue('Trigger_Event__c',configRec.Trigger_Event__c));
            fieldValuesList.add(new MDTFieldValue('Enabled__c',configRec.Enabled__c));
            fieldValuesList.add(new MDTFieldValue('Max_ReEntry__c',configRec.Max_ReEntry__c));
            fieldValuesList.add(new MDTFieldValue('Fields__c',configRec.Fields__c));
            fieldValuesList.add(new MDTFieldValue('Use_New_Transaction__c',configRec.Use_New_Transaction__c));
            fieldValuesList.add(new MDTFieldValue('HandlerClass_ExecutionOrder__c',configRec.HandlerClass_ExecutionOrder__c));
            fieldValuesList.add(new MDTFieldValue('Disabled__c',false));
            metadataRecord.fieldValues = fieldValuesList;
            customMetadataTypes.add(metadataRecord);
        }       
        return upsertMDT('TriggerFrameworkConfig__mdt', customMetadataTypes);
    }
    
    public static string upsertProfileConfig(List<TriggerFrameworkProfileConfig__mdt> profileConfigList){
        List<CustomMetadataType> customMetadataTypes = new List<CustomMetadataType>();
        System.debug('profileConfigList --- '+profileConfigList);
        //List<MDTFieldValue> fieldValuesList = new List<MDTFieldValue>();
        for(TriggerFrameworkProfileConfig__mdt profConfig : profileConfigList){
            CustomMetadataType metadataRecord = new CustomMetadataType();
            //metadataRecord.label = profConfig.DeveloperName+'_'+profConfig.Profile__c+'_'+profConfig.Config__c;
            String devName = profConfig.DeveloperName;//Contains # whic is required to get DeveloperName of objects
            metadataRecord.label = profConfig.Profile__c+'_'+profConfig.Config__c;//To avoid long name exception (max length is 40)
            //fieldValuesList.clear();
            List<MDTFieldValue> fieldValuesList = new List<MDTFieldValue>();
            //fieldValuesList.add(new MDTFieldValue('Id',profConfig.Id));
            fieldValuesList.add(new MDTFieldValue('Profile__c',devName.split('#')[0]));
            fieldValuesList.add(new MDTFieldValue('Config__c',devName.split('#')[1]));
            fieldValuesList.add(new MDTFieldValue('Disabled__c',false));
            metadataRecord.fieldValues = fieldValuesList;
            customMetadataTypes.add(metadataRecord);
        }
        return upsertMDT('TriggerFrameworkProfileConfig__mdt', customMetadataTypes);
    }
    
    public static string disableProfileConfig(List<TriggerFrameworkProfileConfig__mdt> profileConfigList){
        List<CustomMetadataType> customMetadataTypes = new List<CustomMetadataType>();
        List<MDTFieldValue> fieldValuesList = new List<MDTFieldValue>();
        for(TriggerFrameworkProfileConfig__mdt profConfig : profileConfigList){
            CustomMetadataType metadataRecord = new CustomMetadataType();
            //metadataRecord.label = profConfig.DeveloperName+'_'+profConfig.Profile__c+'_'+profConfig.Config__c;
            metadataRecord.label = profConfig.DeveloperName;
            fieldValuesList.clear();
            //fieldValuesList.add(new MDTFieldValue('Id',profConfig.Id));
            fieldValuesList.add(new MDTFieldValue('Disabled__c',profConfig.Disabled__c));
            metadataRecord.fieldValues = fieldValuesList;
            customMetadataTypes.add(metadataRecord);
        }       
        return upsertMDT('TriggerFrameworkProfileConfig__mdt', customMetadataTypes);
    }
    
    public static string disableConfig(List<TriggerFrameworkConfig__mdt> profileConfigList){
        List<CustomMetadataType> customMetadataTypes = new List<CustomMetadataType>();
        List<MDTFieldValue> fieldValuesList = new List<MDTFieldValue>();
        for(TriggerFrameworkConfig__mdt configRec : profileConfigList){
            CustomMetadataType metadataRecord = new CustomMetadataType();
            //metadataRecord.label = configRec.Trigger_Event__c+'_'+configRec.DeveloperName;
            metadataRecord.label = configRec.DeveloperName;
            fieldValuesList.clear();        
            //fieldValuesList.add(new MDTFieldValue('Id',configRec.Id));
            fieldValuesList.add(new MDTFieldValue('Disabled__c',configRec.Disabled__c));
            metadataRecord.fieldValues = fieldValuesList;
            customMetadataTypes.add(metadataRecord);
        }       
        return upsertMDT('TriggerFrameworkConfig__mdt', customMetadataTypes);
    }
    
    public class CustomMetadataType{
        public String label {get; set;}
        public List<MDTFieldValue> fieldValues {get; set;}
    }
    public class MDTFieldValue{
        public MDTFieldValue(String field, Object value){
            this.field = field;
            this.value = value;
        }
        
        public String field {get; set;}
        public Object value {get; set;}
    }
    public static String removeSpclCharsForCustomMD(String strText){
         
        return strText.replaceAll('[^a-zA-Z0-9_\\s+]', '');
    } 
}