CTT_Package/objects/Underlying_Illness__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Contact Outreach, Positive Outreach</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Underlying Illnesses</relationshipLabel>
        <relationshipName>Underlying_Illnesses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Underlying Illness</label>
    <nameField>
        <displayFormat>UI-{00000000}</displayFormat>
        <label>UI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underlying Illnesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CTT_Package/classes/UnderlyingIllnessTriggerHandler.cls
/**
 * Underlying_Illness__c Trigger Handler Class
 *
 * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
 * @since   2020-04-26
 */
public without sharing class UnderlyingIllnessTriggerHandler {

    /**
     * Generic onAfterInsert handler
     */
    public static void onAfterInsert(Map<Id, Underlying_Illness__c> newMap) {
        UpdateCaseExportFields(newMap);
    }
    
    /**
     * Generic onAfterUpdate handler
     */
    public static void onAfterUpdate(Map<Id, Underlying_Illness__c> newMap, Map<Id, Underlying_Illness__c> oldMap){
        UpdateCaseExportFields(newMap);
    }

    /**
     * Generic onBeforeDelete handler
     */
    public static void onBeforeDelete(Map<Id, Underlying_Illness__c> oldMap){
        UpdateCaseExportFields(oldMap);
    }
    
    /**
     * Generic onAfterUndelete handler
     */
    public static void onAfterUndelete(Map<Id, Underlying_Illness__c> newMap){
        UpdateCaseExportFields(newMap);
    }

    /**
     * Any change to the Underlying_Illness__c records should trigger a change to the related cases's export fields
     * 
     * NOTE: The child records are not expected to be transferred between Cases -- they can't be reparented, so we aren't checking
     *       for previous Case__c values.
     *
     * @author  Lawrence Coffin <lawrence.coffin@accenture.com>
     * @since   2020-04-26
     */
    public static void UpdateCaseExportFields(Map<Id, Underlying_Illness__c> recMap)
    {
        Set<Id> caseIds = new Set<Id>();

        // Collect Ids of related cases
        for (Underlying_Illness__c rec : recMap.values())
        {
            caseIds.add(rec.Case__c);
        }
        
        // Call the CaseTriggerHandler method to update the export fields -- specify the UnderlyingIllness fields
        CaseTriggerHandler.UpdateExportFields(caseIds, CaseTriggerHandler.objSpec_UnderlyingIllness);
    }
}